// pki-server/src/ui.nu — Server-rendered Web Interface for PKI management.

$ `stdlib/core/string.nu`

// Base layout wrapper
@ _ui_wrap s title String body String active_nav → String {
    : String out ( string_new )
    ( string_push_str out `<!DOCTYPE html>\n<html lang="en">\n<head>\n` )
    ( string_push_str out `  <meta charset="UTF-8">\n` )
    ( string_push_str out `  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n` )
    ( string_push_str out `  <title>` )
    ( string_push_str out title )
    ( string_push_str out ` - Private PKI Service</title>\n` )
    ( string_push_str out `  <link rel="stylesheet" href="/css/style.css">\n` )
    ( string_push_str out `</head>\n<body>\n` )
    ( string_push_str out `  <div class="container">\n` )
    ( string_push_str out `    <header>\n` )
    ( string_push_str out `      <h1>Private PKI Service</h1>\n` )
    ( string_push_str out `      <p>Pure-NURL Certificate Authority for Internal Devices & Services</p>\n` )
    ( string_push_str out `    </header>\n` )
    ( string_push_str out `    <nav>\n      <ul>\n` )

    ( string_push_str out `        <li><a href="/"` )
    ? ( string_eq active_nav ( string_from `home` ) ) { ( string_push_str out ` class="active"` ) } {}
    ( string_push_str out `>Home</a></li>\n` )

    ( string_push_str out `        <li><a href="/request-cert"` )
    ? ( string_eq active_nav ( string_from `request` ) ) { ( string_push_str out ` class="active"` ) } {}
    ( string_push_str out `>Request Certificate</a></li>\n` )

    ( string_push_str out `        <li><a href="/revoke"` )
    ? ( string_eq active_nav ( string_from `revoke` ) ) { ( string_push_str out ` class="active"` ) } {}
    ( string_push_str out `>Revoke Certificate</a></li>\n` )

    ( string_push_str out `        <li><a href="/crl">Download CRL</a></li>\n` )

    ( string_push_str out `        <li><a href="/ca-cert">Download CA</a></li>\n` )

    ( string_push_str out `        <li><a href="/api"` )
    ? ( string_eq active_nav ( string_from `api` ) ) { ( string_push_str out ` class="active"` ) } {}
    ( string_push_str out `>API Docs</a></li>\n` )

    ( string_push_str out `      </ul>\n    </nav>\n` )
    ( string_push_str out `    <main>\n` )
    ( string_push_str out ( string_data body ) )
    ( string_push_str out `\n    </main>\n` )
    ( string_push_str out `    <footer>\n` )
    ( string_push_str out `      <p>&copy; 2026 Private PKI Service &bull; Powered by pure NURL</p>\n` )
    ( string_push_str out `    </footer>\n` )
    ( string_push_str out `  </div>\n` )
    ( string_push_str out `</body>\n</html>\n` )
    ( string_free body )
    ( string_free active_nav )
    ^ out
}

// ── Pages ─────────────────────────────────────────────────────────────

@ ui_render_index → String {
    : String b ( string_new )
    ( string_push_str b `      <section class="card">\n` )
    ( string_push_str b `        <h2>Welcome to your Private PKI Service</h2>\n` )
    ( string_push_str b `        <p>This service allows you to securely generate, sign, and manage X.509 certificates for internal devices and infrastructure. Built with 100% pure NURL cryptographic primitives.</p>\n` )
    ( string_push_str b `        <div class="features">\n` )
    ( string_push_str b `          <div class="feature">\n` )
    ( string_push_str b `            <h3>Request Certificates</h3>\n` )
    ( string_push_str b `            <p>Generate operational certificates for devices using their initial certificate validation.</p>\n` )
    ( string_push_str b `            <a href="/request-cert" class="button">Request Certificate</a>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="feature">\n` )
    ( string_push_str b `            <h3>Revoke Certificates</h3>\n` )
    ( string_push_str b `            <p>Revoke compromised or retired certificates and update the public Certificate Revocation List.</p>\n` )
    ( string_push_str b `            <a href="/revoke" class="button">Revoke Certificate</a>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="feature">\n` )
    ( string_push_str b `            <h3>REST API</h3>\n` )
    ( string_push_str b `            <p>Full programmatic REST API for automated enrollment, renewal, revocation, and CRL querying.</p>\n` )
    ( string_push_str b `            <a href="/api" class="button">View API Docs</a>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )
    ( string_push_str b `      </section>\n` )
    ^ ( _ui_wrap `Home` b ( string_from `home` ) )
}

@ ui_render_request_cert s error_msg → String {
    : String b ( string_new )
    ( string_push_str b `      <section class="card">\n` )
    ( string_push_str b `        <h2>Request a New Certificate</h2>\n` )
    ? > ( nurl_str_len error_msg ) 0 {
        ( string_push_str b `        <div class="error-message"><p><strong>Error:</strong> ` )
        ( string_push_str b error_msg )
        ( string_push_str b `</p></div>\n` )
    } {}
    ( string_push_str b `        <form action="/request-cert" method="post">\n` )
    ( string_push_str b `          <div class="form-group">\n` )
    ( string_push_str b `            <label for="device_id">Device ID:</label>\n` )
    ( string_push_str b `            <input type="text" id="device_id" name="device_id" required placeholder="e.g. device-001">\n` )
    ( string_push_str b `            <small>Unique identifier for the device (must match initialized certificate)</small>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="form-group">\n` )
    ( string_push_str b `            <label for="initial_cert">Initial Certificate (PEM):</label>\n` )
    ( string_push_str b `            <textarea id="initial_cert" name="initial_cert" required placeholder="-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"></textarea>\n` )
    ( string_push_str b `            <small>Paste your PEM-encoded initial certificate issued during enrollment</small>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="form-group">\n` )
    ( string_push_str b `            <label for="validity_days">Validity (days):</label>\n` )
    ( string_push_str b `            <input type="number" id="validity_days" name="validity_days" value="365" min="1" max="3650">\n` )
    ( string_push_str b `            <small>Operational certificate validity period in days</small>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="form-actions">\n` )
    ( string_push_str b `            <button type="submit" class="button primary">Generate Certificate</button>\n` )
    ( string_push_str b `            <button type="reset" class="button">Reset</button>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </form>\n` )
    ( string_push_str b `      </section>\n` )
    ^ ( _ui_wrap `Request Certificate` b ( string_from `request` ) )
}

@ ui_render_cert_result s device_id s cert s key s ca_cert s expires → String {
    : String b ( string_new )
    ( string_push_str b `      <section class="card">\n` )
    ( string_push_str b `        <h2>Certificate Generated Successfully</h2>\n` )
    ( string_push_str b `        <div class="success-message">\n` )
    ( string_push_str b `          <p>Certificate for device <strong>` )
    ( string_push_str b device_id )
    ( string_push_str b `</strong> has been issued.</p>\n` )
    ( string_push_str b `          <p>Expires at: <strong>` )
    ( string_push_str b expires )
    ( string_push_str b `</strong></p>\n` )
    ( string_push_str b `        </div>\n` )
    ( string_push_str b `        <div class="cert-container">\n` )

    ( string_push_str b `          <div class="cert-section">\n` )
    ( string_push_str b `            <h3>Device Certificate</h3>\n` )
    ( string_push_str b `            <textarea readonly class="cert-text" id="cert_box">` )
    ( string_push_str b cert )
    ( string_push_str b `</textarea>\n` )
    ( string_push_str b `            <div class="button-group">\n` )
    ( string_push_str b `              <button class="button copy-btn" onclick="navigator.clipboard.writeText(document.getElementById('cert_box').value); this.innerText='Copied!';">Copy Certificate</button>\n` )
    ( string_push_str b `            </div>\n` )
    ( string_push_str b `          </div>\n` )

    ( string_push_str b `          <div class="cert-section">\n` )
    ( string_push_str b `            <h3>Private Key</h3>\n` )
    ( string_push_str b `            <textarea readonly class="cert-text" id="key_box">` )
    ( string_push_str b key )
    ( string_push_str b `</textarea>\n` )
    ( string_push_str b `            <div class="button-group">\n` )
    ( string_push_str b `              <button class="button copy-btn" onclick="navigator.clipboard.writeText(document.getElementById('key_box').value); this.innerText='Copied!';">Copy Private Key</button>\n` )
    ( string_push_str b `            </div>\n` )
    ( string_push_str b `            <p class="warning">&iexcl; Keep this private key secure! It is not stored on the server.</p>\n` )
    ( string_push_str b `          </div>\n` )

    ( string_push_str b `          <div class="cert-section">\n` )
    ( string_push_str b `            <h3>CA Certificate</h3>\n` )
    ( string_push_str b `            <textarea readonly class="cert-text" id="ca_box">` )
    ( string_push_str b ca_cert )
    ( string_push_str b `</textarea>\n` )
    ( string_push_str b `            <div class="button-group">\n` )
    ( string_push_str b `              <button class="button copy-btn" onclick="navigator.clipboard.writeText(document.getElementById('ca_box').value); this.innerText='Copied!';">Copy CA Certificate</button>\n` )
    ( string_push_str b `            </div>\n` )
    ( string_push_str b `          </div>\n` )

    ( string_push_str b `        </div>\n` )
    ( string_push_str b `        <div class="action-buttons">\n` )
    ( string_push_str b `          <a href="/request-cert" class="button">Request Another Certificate</a>\n` )
    ( string_push_str b `          <a href="/" class="button primary">Return Home</a>\n` )
    ( string_push_str b `        </div>\n` )
    ( string_push_str b `      </section>\n` )
    ^ ( _ui_wrap `Certificate Generated` b ( string_from `request` ) )
}

@ ui_render_revoke_cert s error_msg → String {
    : String b ( string_new )
    ( string_push_str b `      <section class="card">\n` )
    ( string_push_str b `        <h2>Revoke a Certificate</h2>\n` )
    ? > ( nurl_str_len error_msg ) 0 {
        ( string_push_str b `        <div class="error-message"><p><strong>Error:</strong> ` )
        ( string_push_str b error_msg )
        ( string_push_str b `</p></div>\n` )
    } {}
    ( string_push_str b `        <form action="/revoke" method="post">\n` )
    ( string_push_str b `          <div class="form-group">\n` )
    ( string_push_str b `            <label for="api_key">Management API Key:</label>\n` )
    ( string_push_str b `            <input type="text" id="api_key" name="api_key" required placeholder="your-management-key">\n` )
    ( string_push_str b `            <small>Required authentication key for administrative operations</small>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="form-group">\n` )
    ( string_push_str b `            <label for="serial">Certificate Serial Number (Hex):</label>\n` )
    ( string_push_str b `            <input type="text" id="serial" name="serial" placeholder="e.g. 1a2b3c4d5e6f">\n` )
    ( string_push_str b `            <small>The hexadecimal serial number of the certificate to revoke</small>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="form-group">\n` )
    ( string_push_str b `            <label for="certificate">OR Certificate Content (PEM):</label>\n` )
    ( string_push_str b `            <textarea id="certificate" name="certificate" placeholder="-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"></textarea>\n` )
    ( string_push_str b `            <small>Paste the full PEM-encoded certificate to automatically extract the serial and invalidate initial enrollment</small>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `          <div class="form-actions">\n` )
    ( string_push_str b `            <button type="submit" class="button primary">Revoke Certificate</button>\n` )
    ( string_push_str b `            <button type="reset" class="button">Reset</button>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </form>\n` )
    ( string_push_str b `      </section>\n` )
    ^ ( _ui_wrap `Revoke Certificate` b ( string_from `revoke` ) )
}

@ ui_render_revoke_result s message s serial s revocation_time s crl → String {
    : String b ( string_new )
    ( string_push_str b `      <section class="card">\n` )
    ( string_push_str b `        <h2>Certificate Revoked Successfully</h2>\n` )
    ( string_push_str b `        <div class="success-message">\n` )
    ( string_push_str b `          <p>` )
    ( string_push_str b message )
    ( string_push_str b `</p>\n` )
    ( string_push_str b `          <p>Serial Number: <strong>` )
    ( string_push_str b serial )
    ( string_push_str b `</strong></p>\n` )
    ( string_push_str b `          <p>Revocation Time: <strong>` )
    ( string_push_str b revocation_time )
    ( string_push_str b `</strong></p>\n` )
    ( string_push_str b `        </div>\n` )
    ( string_push_str b `        <div class="cert-container">\n` )
    ( string_push_str b `          <div class="cert-section">\n` )
    ( string_push_str b `            <h3>Updated Certificate Revocation List (CRL)</h3>\n` )
    ( string_push_str b `            <textarea readonly class="cert-text" id="crl_box">` )
    ( string_push_str b crl )
    ( string_push_str b `</textarea>\n` )
    ( string_push_str b `            <div class="button-group">\n` )
    ( string_push_str b `              <button class="button copy-btn" onclick="navigator.clipboard.writeText(document.getElementById('crl_box').value); this.innerText='Copied!';">Copy CRL</button>\n` )
    ( string_push_str b `              <a href="/crl" class="button">Download CRL</a>\n` )
    ( string_push_str b `            </div>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )
    ( string_push_str b `        <div class="action-buttons">\n` )
    ( string_push_str b `          <a href="/revoke" class="button">Revoke Another Certificate</a>\n` )
    ( string_push_str b `          <a href="/" class="button primary">Return Home</a>\n` )
    ( string_push_str b `        </div>\n` )
    ( string_push_str b `      </section>\n` )
    ^ ( _ui_wrap `Certificate Revoked` b ( string_from `revoke` ) )
}

@ ui_render_api_docs → String {
    : String b ( string_new )
    ( string_push_str b `      <section class="card">\n` )
    ( string_push_str b `        <h2>REST API Documentation</h2>\n` )
    ( string_push_str b `        <p>Complete RESTful endpoints for PKI automation and device enrollment.</p>\n` )

    ( string_push_str b `        <div class="api-endpoint">\n` )
    ( string_push_str b `          <h3>POST /init</h3>\n` )
    ( string_push_str b `          <div class="endpoint-details">\n` )
    ( string_push_str b `            <p>Initialize a new device with its initial certificate.</p>\n` )
    ( string_push_str b `            <pre>POST /init\nContent-Type: application/json\n\n{\n  "device_id": "device-001",\n  "key": "your-device-init-key"\n}</pre>\n` )
    ( string_push_str b `            <p><strong>Response (200 OK):</strong></p>\n` )
    ( string_push_str b `            <pre>{\n  "certificate": "-----BEGIN CERTIFICATE-----\\n..."\n}</pre>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )

    ( string_push_str b `        <div class="api-endpoint">\n` )
    ( string_push_str b `          <h3>POST /renew_initial_cert</h3>\n` )
    ( string_push_str b `          <div class="endpoint-details">\n` )
    ( string_push_str b `            <p>Renew an existing initial certificate before expiry.</p>\n` )
    ( string_push_str b `            <pre>POST /renew_initial_cert\nContent-Type: application/json\n\n{\n  "device_id": "device-001",\n  "key": "your-device-init-key",\n  "initial_cert": "-----BEGIN CERTIFICATE-----\\n..."\n}</pre>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )

    ( string_push_str b `        <div class="api-endpoint">\n` )
    ( string_push_str b `          <h3>POST /request-cert</h3>\n` )
    ( string_push_str b `          <div class="endpoint-details">\n` )
    ( string_push_str b `            <p>Issue an operational certificate using initial certificate validation.</p>\n` )
    ( string_push_str b `            <pre>POST /request-cert\nContent-Type: application/json\n\n{\n  "device_id": "device-001",\n  "initial_cert": "-----BEGIN CERTIFICATE-----\\n...",\n  "validity_days": 365\n}</pre>\n` )
    ( string_push_str b `            <p><strong>Response (200 OK):</strong></p>\n` )
    ( string_push_str b `            <pre>{\n  "device_id": "device-001",\n  "certificate": "-----BEGIN CERTIFICATE-----\\n...",\n  "private_key": "-----BEGIN EC PRIVATE KEY-----\\n...",\n  "ca_certificate": "-----BEGIN CERTIFICATE-----\\n...",\n  "expires": "2027-08-18T19:56:04Z"\n}</pre>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )

    ( string_push_str b `        <div class="api-endpoint">\n` )
    ( string_push_str b `          <h3>POST /revoke</h3>\n` )
    ( string_push_str b `          <div class="endpoint-details">\n` )
    ( string_push_str b `            <p>Revoke a certificate by serial number or certificate PEM. Requires management API key.</p>\n` )
    ( string_push_str b `            <pre>POST /revoke\nContent-Type: application/json\nX-API-Key: your-management-key\n\n{\n  "serial": "1a2b3c4d5e6f"\n}</pre>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )

    ( string_push_str b `        <div class="api-endpoint">\n` )
    ( string_push_str b `          <h3>GET /crl</h3>\n` )
    ( string_push_str b `          <div class="endpoint-details">\n` )
    ( string_push_str b `            <p>Download Certificate Revocation List (CRL). Requires management key.</p>\n` )
    ( string_push_str b `            <pre>GET /crl?api_key=your-management-key</pre>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )

    ( string_push_str b `        <div class="api-endpoint">\n` )
    ( string_push_str b `          <h3>GET /ca-cert &bull; GET /health</h3>\n` )
    ( string_push_str b `          <div class="endpoint-details">\n` )
    ( string_push_str b `            <p>Public CA certificate download and service health check.</p>\n` )
    ( string_push_str b `            <pre>GET /ca-cert\nGET /health</pre>\n` )
    ( string_push_str b `          </div>\n` )
    ( string_push_str b `        </div>\n` )

    ( string_push_str b `      </section>\n` )
    ^ ( _ui_wrap `API Documentation` b ( string_from `api` ) )
}

@ ui_default_css → String {
    : String s ( string_new )
    ( string_push_str s `:root{--primary:#1e293b;--secondary:#0284c7;--border:#e2e8f0;--bg:#f8fafc;--card:#fff;--text:#334155;--err:#ef4444;--succ:#10b981;--warn:#f59e0b;}\n` )
    ( string_push_str s `*{box-sizing:border-box;margin:0;padding:0;}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:var(--text);background:var(--bg);padding:24px 16px;line-height:1.6;}\n` )
    ( string_push_str s `.container{max-width:1100px;margin:0 auto;background:var(--card);border-radius:12px;box-shadow:0 4px 6px -1px rgba(0,0,0,0.1);border:1px solid var(--border);overflow:hidden;}\n` )
    ( string_push_str s `header{background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);color:#fff;text-align:center;padding:2.5rem 1.5rem;}header h1{font-size:2rem;margin-bottom:0.5rem;}header p{color:#94a3b8;}\n` )
    ( string_push_str s `nav{background:#0f172a;padding:0.75rem 1.5rem;border-bottom:1px solid #334155;}nav ul{display:flex;flex-wrap:wrap;list-style:none;justify-content:center;gap:0.5rem;}\n` )
    ( string_push_str s `nav ul li a{color:#cbd5e1;text-decoration:none;font-weight:500;font-size:0.95rem;padding:0.5rem 1rem;border-radius:6px;transition:0.2s;}nav ul li a:hover,nav ul li a.active{color:#fff;background:var(--secondary);}\n` )
    ( string_push_str s `main{padding:2rem;}.card{background:#fff;border-radius:6px;}h2{color:var(--primary);font-size:1.5rem;margin-bottom:1.25rem;border-bottom:2px solid #f1f5f9;padding-bottom:0.75rem;}\n` )
    ( string_push_str s `h3{color:var(--primary);font-size:1.2rem;margin:1.5rem 0 0.75rem;}.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1.5rem;margin-top:2rem;}\n` )
    ( string_push_str s `.feature{background:#f1f5f9;padding:1.75rem;border-radius:8px;border:1px solid var(--border);text-align:center;}.feature h3{color:var(--secondary);margin-top:0;}.feature p{color:#475569;margin:1rem 0 1.25rem;}\n` )
    ( string_push_str s `.button{display:inline-block;background:var(--secondary);color:#fff;padding:0.65rem 1.25rem;text-decoration:none;border-radius:6px;border:none;cursor:pointer;font-size:0.95rem;font-weight:500;transition:0.2s;}\n` )
    ( string_push_str s `.button:hover{background:#0369a1;}.button.primary{background:var(--primary);}.button.primary:hover{background:#0f172a;}\n` )
    ( string_push_str s `.form-group{margin-bottom:1.5rem;}label{display:block;margin-bottom:0.5rem;font-weight:600;color:var(--primary);font-size:0.95rem;}\n` )
    ( string_push_str s `input[type="text"],input[type="number"],textarea{width:100%;padding:0.75rem;border:1px solid var(--border);border-radius:6px;font-size:0.95rem;font-family:inherit;background:#fff;}\n` )
    ( string_push_str s `textarea{min-height:160px;font-family:ui-monospace,Menlo,monospace;font-size:0.85rem;resize:vertical;}small{display:block;color:#64748b;margin-top:0.35rem;font-size:0.85rem;}\n` )
    ( string_push_str s `.form-actions{display:flex;gap:1rem;margin-top:1rem;}.cert-container{margin:2rem 0;display:flex;flex-direction:column;gap:1.5rem;}.cert-section{background:#f1f5f9;padding:1.25rem;border-radius:8px;border:1px solid var(--border);}\n` )
    ( string_push_str s `.cert-text{width:100%;height:180px;font-family:ui-monospace,Menlo,monospace;font-size:0.85rem;padding:0.75rem;background:#fff;border:1px solid var(--border);border-radius:6px;margin:0.5rem 0 0.75rem;overflow:auto;}\n` )
    ( string_push_str s `.button-group{display:flex;gap:0.75rem;}.warning{color:var(--warn);font-weight:600;margin-top:0.5rem;font-size:0.9rem;}\n` )
    ( string_push_str s `.error-message{background:#fef2f2;border-left:4px solid var(--err);padding:1rem;border-radius:0 6px 6px 0;margin-bottom:1.5rem;color:#991b1b;}\n` )
    ( string_push_str s `.success-message{background:#ecfdf5;border-left:4px solid var(--succ);padding:1rem;border-radius:0 6px 6px 0;margin-bottom:1.5rem;color:#065f46;}\n` )
    ( string_push_str s `.api-endpoint{margin-bottom:2rem;border:1px solid var(--border);border-radius:6px;overflow:hidden;}.api-endpoint h3{background:#f1f5f9;padding:0.85rem 1.25rem;margin:0;border-bottom:1px solid var(--border);}.endpoint-details{padding:1.25rem;}\n` )
    ( string_push_str s `pre{background:#0f172a;color:#e2e8f0;padding:1rem;border-radius:6px;overflow-x:auto;margin:0.75rem 0;font-family:ui-monospace,Menlo,monospace;font-size:0.85rem;line-height:1.5;}\n` )
    ( string_push_str s `code{font-family:ui-monospace,Menlo,monospace;background:#f1f5f9;padding:0.15rem 0.35rem;border-radius:4px;font-size:0.9em;}\n` )
    ( string_push_str s `.api-info,.crl-info{margin-top:2rem;padding-top:1.5rem;border-top:1px solid var(--border);}.action-buttons{display:flex;gap:1rem;margin-top:1.5rem;}footer{background:#0f172a;color:#94a3b8;text-align:center;padding:1.5rem;font-size:0.9rem;}\n` )
    ^ s
}
