// stdlib/ext/lockfile.nu — typed view over `nurl.lock`.
//
// `nurl.lock` pins the exact resolved version + integrity hash of every
// dependency for source and integrity checks. It is a
// Cargo-shaped lockfile: a `version` format marker plus one
// `[[package]]` block per resolved package, sorted by name for
// deterministic diffs.
//
//   version = 1
//
//   [[package]]
//   name = "foo"
//   version = "1.2.3"
//   source = "registry+https://reg.nurl-lang.org/"
//   checksum = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
//
//   [[package]]
//   name = "localdep"
//   version = "0.1.0"
//
// `source` is a Cargo-style source id (`registry+<url>`); `checksum` is
// the lowercase hex SHA-256 of the package tarball. Both are omitted for
// path/local records made without a source. nurlpkg records their deps/ path
// as source; they have no registry checksum.
//
// API:
//   ( lock_pkg_new name version source checksum ) → LockPkg
//   ( lock_serialize pkgs )    → String                (sorted, deterministic)
//   ( lock_parse src )         → ! ( Vec LockPkg ) LockErr
//   ( lock_load path )         → ! ( Vec LockPkg ) LockErr
//   ( lock_pkg_free p ) / ( lockpkgs_free pkgs ) → v
//   ( lock_err_name e )        → s
//
// String fields use the shared TOML basic-string serializer.

$ `stdlib/core/string.nu`
$ `stdlib/core/vec.nu`
$ `stdlib/ext/toml.nu`
$ `stdlib/std/sort.nu`
$ `stdlib/std/cmp.nu`
$ `stdlib/std/fs.nu`

: LockPkg {
    String name
    String version
    String source  // "registry+<url>"; empty for path/local
    String checksum  // hex SHA-256 of the tarball; empty for path/local
}

: | LockErr {
    LockParseFailed  // TOML didn't parse
    LockReadFailed  // file couldn't be read
    LockBadShape  // `package` present but not an array-of-tables
}

@ lock_err_name LockErr e → s {
    ^ ?? e {
        LockParseFailed → `LockParseFailed`
        LockReadFailed → `LockReadFailed`
        LockBadShape → `LockBadShape`
    }
}

@ lock_pkg_new s name s version s source s checksum → LockPkg {
    ^ @ LockPkg {
        ( string_from name )
        ( string_from version )
        ( string_from source )
        ( string_from checksum )
    }
}

@ lock_pkg_free sink LockPkg p → v {
    ( string_free . p name )
    ( string_free . p version )
    ( string_free . p source )
    ( string_free . p checksum )
}

@ lockpkgs_free sink ( Vec LockPkg ) pkgs → v {
    : i n ( vec_len [LockPkg] pkgs )
    : ~ i k 0
    ~ < k n {
        : ?LockPkg po ( vec_get [LockPkg] pkgs k )
        ?? po { T p → ( lock_pkg_free p ) F → {} }
        = k + k 1
    }
    ( vec_free [LockPkg] pkgs )
}

// ── Serialize ─────────────────────────────────────────────────────────

@ __lock_kv String out s key s val → v {
    ( string_push_str out key )
    ( string_push_str out ` = ` )
    ( toml_append_quoted out val )
    ( string_push_char out 10 )
}

// Compare the complete identity before the payload. Equal names from
// different registries must serialize deterministically in either root order.
@ __lock_pkg_cmp LockPkg a LockPkg b → i {
    : i name ( cmp_string . a name . b name )
    ? != name 0 { ^ name } {}
    : i source ( cmp_string . a source . b source )
    ? != source 0 { ^ source } {}
    : i version ( cmp_string . a version . b version )
    ? != version 0 { ^ version } {}
    ^ ( cmp_string . a checksum . b checksum )
}

// Sort borrowed record pointers: one word per package, no record copies and
// no comparator environment. The caller's vector remains unchanged.
@ __lock_sorted_order ( Vec LockPkg ) pkgs → ( Vec * LockPkg ) {
    : i n ( vec_len [LockPkg] pkgs )
    : ( Vec * LockPkg ) order ( vec_with_cap [* LockPkg] n )
    : *LockPkg data ( vec_data [LockPkg] pkgs )
    : ~ i k 0
    ~ < k n {
        ( vec_push [* LockPkg] order # *LockPkg + # i data * k Z LockPkg )
        = k + k 1
    }
    ( sort_by [* LockPkg] order \ * LockPkg a * LockPkg b → i { ^ ( __lock_pkg_cmp . a 0 . b 0 ) } )
    ^ order
}

@ lock_serialize ( Vec LockPkg ) pkgs → String {
    : String out ( string_with_cap 256 )
    ( string_push_str out `# Auto-generated by nurlpkg — do not edit.\n` )
    ( string_push_str out `version = 1\n` )
    : i n ( vec_len [LockPkg] pkgs )
    : ( Vec * LockPkg ) order ( __lock_sorted_order pkgs )
    : ~ i i 0
    ~ < i n {
        ?? ( vec_get [* LockPkg] order i ) {
            T ptr → {
                : LockPkg p . ptr 0
                ( string_push_str out `\n[[package]]\n` )
                ( __lock_kv out `name` ( string_data . p name ) )
                ( __lock_kv out `version` ( string_data . p version ) )
                ? > ( string_len . p source ) 0 {
                    ( __lock_kv out `source` ( string_data . p source ) )
                } {}
                ? > ( string_len . p checksum ) 0 {
                    ( __lock_kv out `checksum` ( string_data . p checksum ) )
                } {}
            }
            F → {}
        }
        = i + i 1
    }
    ( vec_free [* LockPkg] order )
    ^ out
}

// ── Parse ─────────────────────────────────────────────────────────────

@ __lock_get_str TomlValue tbl s key → String {
    : ~ String out ( string_new )
    : ?TomlValue v ( toml_get tbl key )
    ?? v {
        T tv → {
            : ?String s ( toml_as_str tv )
            ?? s { T sv → { ( string_free out ) = out sv } F empty → ( string_free empty ) }
        }
        F → {}
    }
    ^ out
}

@ lock_parse s src → !( Vec LockPkg ) LockErr {
    : !TomlValue TomlErr tr ( toml_parse src )
    ?? tr {
        F _ → ^ @ !( Vec LockPkg ) LockErr { F # LockErr LockParseFailed }
        T root → {
            : ( Vec LockPkg ) out ( vec_new [LockPkg] )
            : ~ i shape_ok 1
            : ?TomlValue pa ( toml_get root `package` )
            ?? pa {
                T pv → {
                    ?? pv {
                        TArr arr → {
                            : i n ( vec_len [TomlValue] arr )
                            : ~ i k 0
                            ~ < k n {
                                : ?TomlValue eo ( vec_get [TomlValue] arr k )
                                ?? eo {
                                    T tbl → {
                                        : String nm ( __lock_get_str tbl `name` )
                                        : String ver ( __lock_get_str tbl `version` )
                                        : String src2 ( __lock_get_str tbl `source` )
                                        : String chk ( __lock_get_str tbl `checksum` )
                                        ( vec_push [LockPkg] out @ LockPkg { nm ver src2 chk } )
                                    }
                                    F → {}
                                }
                                = k + k 1
                            }
                        }
                        _ → { = shape_ok 0 }
                    }
                }
                F → {}
            }
            ( toml_value_free root )
            ? == shape_ok 0 {
                ( lockpkgs_free out )
                ^ @ !( Vec LockPkg ) LockErr { F # LockErr LockBadShape }
            } {}
            ^ @ !( Vec LockPkg ) LockErr { T out }
        }
    }
}

@ lock_load s path → !( Vec LockPkg ) LockErr {
    ?? ( read_file path ) {
        F _ → { ^ @ !( Vec LockPkg ) LockErr { F LockReadFailed } }
        T text → {
            : !( Vec LockPkg ) LockErr result ( lock_parse ( string_data text ) )
            ( string_free text )
            ^ result
        }
    }
}
