// stdlib/ext/lockfile.nu — typed view over `nurl.lock`.
//
// `nurl.lock` pins the exact resolved version + integrity hash of every
// dependency so an install is reproducible and tamper-evident. It is a
// Cargo-shaped lockfile: a `version` format marker plus one
// `[[package]]` block per resolved package, sorted by name for
// deterministic diffs.
//
//   version = 1
//
//   [[package]]
//   name = "foo"
//   version = "1.2.3"
//   source = "registry+https://reg.nurl-lang.org/"
//   checksum = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
//
//   [[package]]
//   name = "localdep"
//   version = "0.1.0"
//
// `source` is a Cargo-style source id (`registry+<url>`); `checksum` is
// the lowercase hex SHA-256 of the package tarball. Both are omitted for
// path/local packages (they have no registry identity or stable hash).
//
// API:
//   ( lock_pkg_new name version source checksum ) → LockPkg
//   ( lock_serialize pkgs )    → String                (sorted, deterministic)
//   ( lock_parse src )         → ! ( Vec LockPkg ) LockErr
//   ( lock_load path )         → ! ( Vec LockPkg ) LockErr
//   ( lock_pkg_free p ) / ( lockpkgs_free pkgs ) → v
//   ( lock_err_name e )        → s
//
// v1: like nurlpkg's original lock writer, string fields are NOT escaped
// — names/versions/source-urls/hex digests contain none of TOML's
// basic-string metacharacters (" \ newline). A hand-crafted lock with
// such a value would need real escaping.

$ `stdlib/core/string.nu`
$ `stdlib/core/vec.nu`
$ `stdlib/ext/toml.nu`

: LockPkg {
    String name
    String version
    String source  // "registry+<url>"; empty for path/local
    String checksum  // hex SHA-256 of the tarball; empty for path/local
}

: | LockErr {
    LockParseFailed  // TOML didn't parse
    LockReadFailed  // file couldn't be read
    LockBadShape  // `package` present but not an array-of-tables
}

@ lock_err_name LockErr e → s {
    ^ ?? e {
        LockParseFailed → `LockParseFailed`
        LockReadFailed → `LockReadFailed`
        LockBadShape → `LockBadShape`
    }
}

@ lock_pkg_new s name s version s source s checksum → LockPkg {
    ^ @ LockPkg {
        ( string_from name )
        ( string_from version )
        ( string_from source )
        ( string_from checksum )
    }
}

@ lock_pkg_free LockPkg p → v {
    ( string_free . p name )
    ( string_free . p version )
    ( string_free . p source )
    ( string_free . p checksum )
}

@ lockpkgs_free ( Vec LockPkg ) pkgs → v {
    : i n ( vec_len [LockPkg] pkgs )
    : ~ i k 0
    ~ < k n {
        : ?LockPkg po ( vec_get [LockPkg] pkgs k )
        ?? po { T p → ( lock_pkg_free p ) F → {} }
        = k + k 1
    }
    ( vec_free [LockPkg] pkgs )
}

// ── Serialize ─────────────────────────────────────────────────────────

@ __lock_kv String out s key s val → v {
    ( string_push_str out key )
    ( string_push_str out ` = "` )
    ( string_push_str out val )
    ( string_push_str out `"\n` )
}

// Lexical byte comparison: a < b ?
@ __lock_name_lt s a s b → b {
    : i an ( nurl_str_len a )
    : i bn ( nurl_str_len b )
    : i m ? < an bn an bn
    : ~ i k 0
    ~ < k m {
        : i ca ( nurl_str_get a k )
        : i cb ( nurl_str_get b k )
        ? < ca cb { ^ T } {}
        ? > ca cb { ^ F } {}
        = k + k 1
    }
    ^ < an bn
}

// Selection-sort the package indices by name; returns a fresh index Vec.
@ __lock_sorted_order ( Vec LockPkg ) pkgs → ( Vec i ) {
    : i n ( vec_len [LockPkg] pkgs )
    : ( Vec i ) order ( vec_with_cap [i] ? > n 0 n 1 )
    : ~ i i 0
    ~ < i n { ( vec_push [i] order i ) = i + i 1 }
    : ~ i a 0
    ~ < a n {
        : ~ i best a
        : ~ i b + a 1
        ~ < b n {
            : i ib ?? ( vec_get [i] order b ) { T x → x F → 0 }
            : i ibest ?? ( vec_get [i] order best ) { T x → x F → 0 }
            : s nb ?? ( vec_get [LockPkg] pkgs ib ) { T p → ( string_data . p name ) F → `` }
            : s nbest ?? ( vec_get [LockPkg] pkgs ibest ) { T p → ( string_data . p name ) F → `` }
            ? ( __lock_name_lt nb nbest ) { = best b } {}
            = b + b 1
        }
        ? != best a {
            : i ta ?? ( vec_get [i] order a ) { T x → x F → 0 }
            : i tb ?? ( vec_get [i] order best ) { T x → x F → 0 }
            ( vec_set [i] order a tb )
            ( vec_set [i] order best ta )
        } {}
        = a + a 1
    }
    ^ order
}

@ lock_serialize ( Vec LockPkg ) pkgs → String {
    : String out ( string_with_cap 256 )
    ( string_push_str out `# Auto-generated by nurlpkg — do not edit.\n` )
    ( string_push_str out `version = 1\n` )
    : i n ( vec_len [LockPkg] pkgs )
    : ( Vec i ) order ( __lock_sorted_order pkgs )
    : ~ i i 0
    ~ < i n {
        : i idx ?? ( vec_get [i] order i ) { T x → x F → 0 }
        : ?LockPkg po ( vec_get [LockPkg] pkgs idx )
        ?? po {
            T p → {
                ( string_push_str out `\n[[package]]\n` )
                ( __lock_kv out `name` ( string_data . p name ) )
                ( __lock_kv out `version` ( string_data . p version ) )
                ? > ( string_len . p source ) 0 {
                    ( __lock_kv out `source` ( string_data . p source ) )
                } {}
                ? > ( string_len . p checksum ) 0 {
                    ( __lock_kv out `checksum` ( string_data . p checksum ) )
                } {}
            }
            F → {}
        }
        = i + i 1
    }
    ( vec_free [i] order )
    ^ out
}

// ── Parse ─────────────────────────────────────────────────────────────

@ __lock_get_str TomlValue tbl s key → String {
    : ~ String out ( string_new )
    : ?TomlValue v ( toml_get tbl key )
    ?? v {
        T tv → {
            : ?String s ( toml_as_str tv )
            ?? s { T sv → { ( string_free out ) = out sv } F empty → ( string_free empty ) }
        }
        F → {}
    }
    ^ out
}

@ lock_parse s src → !( Vec LockPkg ) LockErr {
    : !TomlValue TomlErr tr ( toml_parse src )
    ?? tr {
        F _ → ^ @ !( Vec LockPkg ) LockErr { F # LockErr LockParseFailed }
        T root → {
            : ( Vec LockPkg ) out ( vec_new [LockPkg] )
            : ~ i shape_ok 1
            : ?TomlValue pa ( toml_get root `package` )
            ?? pa {
                T pv → {
                    ?? pv {
                        TArr arr → {
                            : i n ( vec_len [TomlValue] arr )
                            : ~ i k 0
                            ~ < k n {
                                : ?TomlValue eo ( vec_get [TomlValue] arr k )
                                ?? eo {
                                    T tbl → {
                                        : String nm ( __lock_get_str tbl `name` )
                                        : String ver ( __lock_get_str tbl `version` )
                                        : String src2 ( __lock_get_str tbl `source` )
                                        : String chk ( __lock_get_str tbl `checksum` )
                                        ( vec_push [LockPkg] out @ LockPkg { nm ver src2 chk } )
                                    }
                                    F → {}
                                }
                                = k + k 1
                            }
                        }
                        _ → { = shape_ok 0 }
                    }
                }
                F → {}
            }
            ( toml_value_free root )
            ? == shape_ok 0 {
                ( lockpkgs_free out )
                ^ @ !( Vec LockPkg ) LockErr { F # LockErr LockBadShape }
            } {}
            ^ @ !( Vec LockPkg ) LockErr { T out }
        }
    }
}

@ lock_load s path → !( Vec LockPkg ) LockErr {
    : s raw ( nurl_read_file path )
    ? == 0 ( nurl_str_len raw ) {
        ^ @ !( Vec LockPkg ) LockErr { F # LockErr LockReadFailed }
    } {}
    ^ ( lock_parse raw )
}
