#!/usr/bin/env python3
# Regenerate src/clip_merges_data.nu from assets/clip_merges.txt.
#
# The CLIP BPE merges are a runtime asset, but `nurlpkg install` ships
# only the built binary — a file on disk can never be found from an
# installed tool. Embedding the table makes every binary that links
# bpe.nu self-contained (`tokenizer_load_builtin`); --merges stays as
# an override for custom vocabularies.
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "assets" / "clip_merges.txt").read_text(encoding="utf-8")
# NURL backtick literals take raw newlines; backslash starts an escape.
body = src.replace("\\", "\\\\")
assert "`" not in src, "merges must not contain backticks"

out = root / "src" / "clip_merges_data.nu"
out.write_text(
    "// GENERATED by tools/embed_merges.py from assets/clip_merges.txt — do not edit.\n"
    "// The CLIP BPE merge table (48893 lines), embedded so installed binaries\n"
    "// need no asset file on disk (see tokenizer_load_builtin in bpe.nu).\n"
    "\n"
    "@ clip_merges_data → s {\n"
    "    ^ `" + body + "`\n"
    "}\n",
    encoding="utf-8",
)
print(f"wrote {out} ({out.stat().st_size} bytes)")
