#!/usr/bin/env python3
# Regenerate src/clip_merges_data.nu from assets/clip_merges.txt.
#
# The CLIP BPE merges are a runtime asset, but `nurlpkg install` ships
# only the built binary — a file on disk can never be found from an
# installed tool. Embedding the table makes every binary that links
# bpe.nu self-contained (`tokenizer_load_builtin`); --merges stays as
# an override for custom vocabularies.
#
# The table is emitted as ~32 KB CHUNKS, split on line boundaries:
# released compilers up to v0.11.1 encode string literals with a
# per-character recursion that overflows the stack — the zig -O2 -flto
# RELEASE builds crash already past ~48 KB (dev builds ~124 KB) — and a
# registry package must build with the toolchain users actually have.
# (main's nurlc encodes iteratively and takes any size — the chunking
# is for compatibility, not correctness.)
import pathlib

CHUNK = 32 * 1024

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "assets" / "clip_merges.txt").read_text(encoding="utf-8")
assert "`" not in src, "merges must not contain backticks"

# split on line boundaries so no \\ escape straddles a chunk edge
chunks, pos = [], 0
while pos < len(src):
    end = min(pos + CHUNK, len(src))
    if end < len(src):
        nl = src.rfind("\n", pos, end)
        assert nl > pos, "line longer than a chunk?"
        end = nl + 1
    # NURL backtick literals take raw newlines; backslash starts an escape
    chunks.append(src[pos:end].replace("\\", "\\\\"))
    pos = end

arms = "".join(
    "    ? == k %d { ^ `%s` } {}\n" % (i, c) for i, c in enumerate(chunks)
)
out = root / "src" / "clip_merges_data.nu"
out.write_text(
    "// GENERATED by tools/embed_merges.py from assets/clip_merges.txt — do not edit.\n"
    "// The CLIP BPE merge table (48893 lines) in ~32 KB line-aligned chunks,\n"
    "// embedded so installed binaries need no asset file on disk (see\n"
    "// tokenizer_load_builtin in bpe.nu). Chunked because released nurlc\n"
    "// (≤ v0.11.1) stack-overflows on string literals past ~48 KB.\n"
    "\n"
    "@ clip_merges_chunks → i {\n"
    "    ^ %d\n"
    "}\n"
    "\n"
    "@ clip_merges_chunk i k → s {\n"
    "%s"
    "    ^ ``\n"
    "}\n" % (len(chunks), arms),
    encoding="utf-8",
)
print(f"wrote {out} ({out.stat().st_size} bytes, {len(chunks)} chunks)")
