#!/usr/bin/env python3
# Regenerate src/index_html_data.nu from views/index.html.
#
# The demo page template is a runtime asset, but `nurlpkg install`
# ships only the built binary — a relative views/ path can never
# resolve for an installed tool (the same failure the embedded CLIP
# merges fixed in packages/yoloe). The template is compiled into the
# binary; --page FILE stays as an override for customized pages.
#
# Emitted as ~32 KB line-aligned chunks: released nurlc (≤ v0.11.1)
# stack-overflows past ~48 KB per string literal (zig -O2 -flto build),
# and a registry package must build with the toolchain users have.
import pathlib

CHUNK = 32 * 1024

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "views" / "index.html").read_text(encoding="utf-8")
assert "`" not in src, "index.html must not contain backticks (NURL literal delimiter)"

chunks, pos = [], 0
while pos < len(src):
    end = min(pos + CHUNK, len(src))
    if end < len(src):
        nl = src.rfind("\n", pos, end)
        assert nl > pos, "line longer than a chunk?"
        end = nl + 1
    # NURL backtick literals take raw newlines; backslash starts an escape
    chunks.append(src[pos:end].replace("\\", "\\\\"))
    pos = end

arms = "".join(
    "    ? == k %d { ^ `%s` } {}\n" % (i, c) for i, c in enumerate(chunks)
)
out = root / "src" / "index_html_data.nu"
out.write_text(
    "// GENERATED by tools/embed_page.py from views/index.html — do not edit.\n"
    "// The demo page template, embedded so installed binaries need no\n"
    "// views/ directory on disk (--page FILE overrides). Chunked because\n"
    "// released nurlc (≤ v0.11.1) stack-overflows on literals past ~48 KB.\n"
    "\n"
    "@ index_html_chunks → i {\n"
    "    ^ %d\n"
    "}\n"
    "\n"
    "@ index_html_chunk i k → s {\n"
    "%s"
    "    ^ ``\n"
    "}\n" % (len(chunks), arms),
    encoding="utf-8",
)
print(f"wrote {out} ({out.stat().st_size} bytes, {len(chunks)} chunks)")
