#!/usr/bin/env python3
# Regenerate src/viewer_html_data.nu from views/viewer.html.
#
# `nurlpkg install` ships the built binary and nothing else, so a
# views/ path next to the executable can never resolve for an installed
# tool. The page is compiled in; `--page FILE` stays as an override for
# working on it.
#
# Emitted as ~32 KB line-aligned chunks: released nurlc stack-overflows
# past ~48 KB in a single string literal, and a registry package has to
# build with the toolchain users actually have.
import pathlib

CHUNK = 32 * 1024

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "views" / "viewer.html").read_text(encoding="utf-8")
assert "`" not in src, "viewer.html must not contain backticks (NURL literal delimiter)"

chunks, pos = [], 0
while pos < len(src):
    end = min(pos + CHUNK, len(src))
    if end < len(src):
        nl = src.rfind("\n", pos, end)
        assert nl > pos, "line longer than a chunk?"
        end = nl + 1
    # NURL backtick literals take raw newlines; backslash starts an escape
    chunks.append(src[pos:end].replace("\\", "\\\\"))
    pos = end

arms = "".join(
    "    ? == k %d { ^ `%s` } {}\n" % (i, c) for i, c in enumerate(chunks)
)
out = root / "src" / "viewer_html_data.nu"
out.write_text(
    "// GENERATED by tools/embed_viewer.py from views/viewer.html — do not edit.\n"
    "// The viewer page, embedded so an installed binary needs no views/\n"
    "// directory on disk (--page FILE overrides). Chunked because released\n"
    "// nurlc stack-overflows on string literals past ~48 KB.\n"
    "\n"
    "@ viewer_html_chunks → i {\n"
    "    ^ %d\n"
    "}\n"
    "\n"
    "@ viewer_html_chunk i k → s {\n"
    "%s"
    "    ^ ``\n"
    "}\n" % (len(chunks), arms),
    encoding="utf-8",
)
print("wrote %s (%d bytes, %d chunks)" % (out, out.stat().st_size, len(chunks)))
