/*
 * NURL nolibc — unikernel/nolibc/math_tables.h
 *
 * Copyright (c) 2026 The NURL Project Developers
 * SPDX-License-Identifier: MIT OR Apache-2.0
 *
 * GENERATED by tools/gen_libm_tables.py — do not edit. Every
 * coefficient is a Chebyshev interpolation of the exact function at
 * 60 digits, solved in 80-digit decimal; the measured fit error is
 * printed above each one so the choice of degree is visible rather
 * than folklore.
 */
#ifndef NURL_NOLIBC_MATH_TABLES_H
#define NURL_NOLIBC_MATH_TABLES_H

/* E(r) = (exp(r) - 1 - r) / r^2, the tail of exp after its two exact terms.
   degree 13 on [-0.346574, 0.346574]; worst relative fit error 4.621E-24 */
static const double NL_EXP_P[14] = {
    0x1.0000000000000p-1,   /* x^0 */
    0x1.5555555555555p-3,   /* x^1 */
    0x1.5555555555555p-5,   /* x^2 */
    0x1.1111111111111p-7,   /* x^3 */
    0x1.6c16c16c16c18p-10,   /* x^4 */
    0x1.a01a01a01a01bp-13,   /* x^5 */
    0x1.a01a01a0192eap-16,   /* x^6 */
    0x1.71de3a556c0ffp-19,   /* x^7 */
    0x1.27e4fb7c70cd8p-22,   /* x^8 */
    0x1.ae645683f12e2p-26,   /* x^9 */
    0x1.1eed71134c700p-29,   /* x^10 */
    0x1.61244511b70acp-33,   /* x^11 */
    0x1.944c6bf0a759fp-37,   /* x^12 */
    0x1.af29b46646768p-41,   /* x^13 */
};

/* A(z) = (atanh(s)/s - 1) / z with z = s^2; log of the reduced mantissa.
   degree 11 on [0, 0.0294373]; worst relative fit error 6.689E-27 */
static const double NL_LOG_P[12] = {
    0x1.5555555555555p-2,   /* x^0 */
    0x1.999999999999ap-3,   /* x^1 */
    0x1.2492492492492p-3,   /* x^2 */
    0x1.c71c71c71c71ep-4,   /* x^3 */
    0x1.745d1745d153cp-4,   /* x^4 */
    0x1.3b13b13b2c455p-4,   /* x^5 */
    0x1.11111105568e5p-4,   /* x^6 */
    0x1.e1e1e93de1625p-5,   /* x^7 */
    0x1.af26e237d3a2ep-5,   /* x^8 */
    0x1.864e83f5283c5p-5,   /* x^9 */
    0x1.5f7b27815d42bp-5,   /* x^10 */
    0x1.8296acfcbe969p-5,   /* x^11 */
};

/* S(z) = (sin(r) - r) / r^3 with z = r^2.
   degree 8 on [0, 0.61685]; worst relative fit error 1.187E-26 */
static const double NL_SIN_P[9] = {
    -0x1.5555555555555p-3,   /* x^0 */
    0x1.1111111111111p-7,   /* x^1 */
    -0x1.a01a01a01a01ap-13,   /* x^2 */
    0x1.71de3a556c733p-19,   /* x^3 */
    -0x1.ae64567f54151p-26,   /* x^4 */
    0x1.6124613a00f03p-33,   /* x^5 */
    -0x1.ae7f3d02d36a2p-41,   /* x^6 */
    0x1.952a280855aecp-49,   /* x^7 */
    -0x1.2d4a336a728d1p-57,   /* x^8 */
};

/* C(z) = (cos(r) - 1 + z/2) / z^2 with z = r^2.
   degree 8 on [0, 0.61685]; worst relative fit error 2.137E-27 */
static const double NL_COS_P[9] = {
    0x1.5555555555555p-5,   /* x^0 */
    -0x1.6c16c16c16c17p-10,   /* x^1 */
    0x1.a01a01a01a01ap-16,   /* x^2 */
    -0x1.27e4fb7789f5cp-22,   /* x^3 */
    0x1.1eed8eff8d74bp-29,   /* x^4 */
    -0x1.93974a8ba661fp-37,   /* x^5 */
    0x1.ae7f3d6731a37p-45,   /* x^6 */
    -0x1.6825d846fd835p-53,   /* x^7 */
    0x1.e25a860c767adp-62,   /* x^8 */
};

/* T(z) = (tan(r) - r) / r^3 with z = r^2, |r| <= pi/4.
   degree 22 on [0, 0.61685]; worst relative fit error 9.695E-27 */
static const double NL_TAN_P[23] = {
    0x1.5555555555555p-2,   /* x^0 */
    0x1.1111111111111p-3,   /* x^1 */
    0x1.ba1ba1ba1ba1cp-5,   /* x^2 */
    0x1.664f4882c10fap-6,   /* x^3 */
    0x1.226e355e6c243p-7,   /* x^4 */
    0x1.d6d3d0e157a54p-9,   /* x^5 */
    0x1.7da36452c2493p-10,   /* x^6 */
    0x1.3558247eb96e5p-11,   /* x^7 */
    0x1.f57d778168f1ap-13,   /* x^8 */
    0x1.967e12d8da0a0p-14,   /* x^9 */
    0x1.497de72d230bcp-15,   /* x^10 */
    0x1.0b0f14d9dc5bap-16,   /* x^11 */
    0x1.b144686b9b78ep-18,   /* x^12 */
    0x1.5cad30591f1bbp-19,   /* x^13 */
    0x1.2a2b39ab0dad0p-20,   /* x^14 */
    0x1.4911608bf97e7p-22,   /* x^15 */
    0x1.b80081c5d6667p-22,   /* x^16 */
    -0x1.317b51932caafp-22,   /* x^17 */
    0x1.d9c5124721d7bp-22,   /* x^18 */
    -0x1.74fb0d075e43cp-22,   /* x^19 */
    0x1.e6c87a1414f26p-23,   /* x^20 */
    -0x1.74174db73b0c0p-24,   /* x^21 */
    0x1.41b6718e3e25dp-26,   /* x^22 */
};

/* A(z) = (atan(w) - w) / w^3 with z = w^2, |w| < 7/16.
   degree 15 on [0, 0.191406]; worst relative fit error 3.337E-23 */
static const double NL_ATAN_P[16] = {
    -0x1.5555555555555p-2,   /* x^0 */
    0x1.999999999999ap-3,   /* x^1 */
    -0x1.2492492492492p-3,   /* x^2 */
    0x1.c71c71c71c674p-4,   /* x^3 */
    -0x1.745d1745cda78p-4,   /* x^4 */
    0x1.3b13b13a3e7b2p-4,   /* x^5 */
    -0x1.111110f255ae0p-4,   /* x^6 */
    0x1.e1e1dbbef50e7p-5,   /* x^7 */
    -0x1.af27fb7a99ca2p-5,   /* x^8 */
    0x1.861282d7ec831p-5,   /* x^9 */
    -0x1.63f27a1c6a753p-5,   /* x^10 */
    0x1.4604d17001594p-5,   /* x^11 */
    -0x1.2671907ed2961p-5,   /* x^12 */
    0x1.eec90fd8c5826p-6,   /* x^13 */
    -0x1.4e33c665d47ffp-6,   /* x^14 */
    0x1.00f6f48ee51c0p-7,   /* x^15 */
};

/* atan's reduction targets: atan(0.5), atan(1), atan(1.5), pi/2,
   each as head + tail so the head is exact and the tail carries
   what a single double cannot. */
static const double NL_ATAN_HI[4] = {
    0x1.dac670561bb4fp-2,
    0x1.921fb54442d18p-1,
    0x1.f730bd281f69bp-1,
    0x1.921fb54442d18p+0,
};

static const double NL_ATAN_LO[4] = {
    0x1.a2b7f222f65e2p-56,
    0x1.1a62633145c07p-55,
    0x1.007887af0cbbdp-56,
    0x1.1a62633145c07p-54,
};

#define NL_LN2_HI  0x1.62e42fef00000p-1
#define NL_LN2_LO  0x1.473de6af278edp-34
#define NL_IVLN2_HI  0x1.7154765200000p+0
#define NL_IVLN2_LO  0x1.705fc2eefa200p-33
#define NL_LG2_HI  0x1.3441350800000p-2
#define NL_LG2_LO  0x1.f79fef311f12bp-34
#define NL_IVLN10_HI  0x1.bcb7b15200000p-2
#define NL_IVLN10_LO  0x1.b9438ca9aadd5p-36
#define NL_PIO2_HI  0x1.921fb54400000p+0
#define NL_PIO2_LO  0x1.0b4611a626331p-34
#define NL_PI_HI  0x1.921fb54400000p+1
#define NL_PI_LO  0x1.0b4611a626331p-33
#define NL_PI_D  0x1.921fb54442d18p+1
#define NL_PI_T  0x1.1a62633145c07p-53
#define NL_PIO2_D  0x1.921fb54442d18p+0
#define NL_PIO2_T  0x1.1a62633145c07p-54
#define NL_2_OVER_PI  0x1.45f306dc9c883p-1
#define NL_SQRT2      0x1.6a09e667f3bcdp+0

/* E(z) = erf(x)/x with z = x^2, |x| <= 1.
   degree 16 on [0, 1]; worst relative fit error 7.627E-27 */
static const double NL_ERF_P[17] = {
    0x1.20dd750429b6dp+0,   /* x^0 */
    -0x1.812746b0379e7p-2,   /* x^1 */
    0x1.ce2f21a042be2p-4,   /* x^2 */
    -0x1.b82ce31288b51p-6,   /* x^3 */
    0x1.565bcd0e6a53fp-8,   /* x^4 */
    -0x1.c02db40040b65p-11,   /* x^5 */
    0x1.f9a326f9b81acp-14,   /* x^6 */
    -0x1.f4d25c3df5bfap-17,   /* x^7 */
    0x1.b9e6c9d9947e4p-20,   /* x^8 */
    -0x1.5f742e81b0304p-23,   /* x^9 */
    0x1.fcc568dbc98f8p-27,   /* x^10 */
    -0x1.51d69f1d77078p-30,   /* x^11 */
    0x1.9e6185e93545bp-34,   /* x^12 */
    -0x1.d7be16814e9efp-38,   /* x^13 */
    0x1.f1040f7034f61p-42,   /* x^14 */
    -0x1.ce349ffbeee2fp-46,   /* x^15 */
    0x1.27004fc3eb71fp-50,   /* x^16 */
};

#define NL_ERF_P_N 17

/* erfc(a) directly, 0.5 <= a <= 1.
   degree 20 on [0.5, 1], in the centred
   variable v = (x - MID) * INVHALF; worst relative fit error 2.154E-27 */
#define NL_ERFC_D_MID     0x1.8000000000000p-1
#define NL_ERFC_D_INVHALF 0x1.0000000000000p+2
static const double NL_ERFC_D[21] = {
    0x1.27c6d14c5e341p-2,   /* v^0 */
    -0x1.492e42d78d2c5p-3,   /* v^1 */
    0x1.edc5644353c27p-6,   /* v^2 */
    -0x1.b6e8591f66e5bp-12,   /* v^3 */
    -0x1.349b5eaa14598p-11,   /* v^4 */
    0x1.b42a1890ce411p-15,   /* v^5 */
    0x1.b8477966b3381p-18,   /* v^6 */
    -0x1.2e0afb0bb961ep-20,   /* v^7 */
    -0x1.2db332f9e64ddp-25,   /* v^8 */
    0x1.04105cd6d52ddp-26,   /* v^9 */
    -0x1.86234ec3344e3p-33,   /* v^10 */
    -0x1.4725abcba2effp-33,   /* v^11 */
    0x1.bd5eea722f5f5p-38,   /* v^12 */
    0x1.3db33dc8203cdp-40,   /* v^13 */
    -0x1.7313facc75795p-44,   /* v^14 */
    -0x1.e0eaf95221330p-48,   /* v^15 */
    0x1.b48292c38f2f9p-51,   /* v^16 */
    0x1.0e4bee8fb9208p-55,   /* v^17 */
    -0x1.9a139279d73b4p-58,   /* v^18 */
    -0x1.5a60614cb89d5p-64,   /* v^19 */
    0x1.3ad2cfd295415p-65,   /* v^20 */
};

#define NL_ERFC_D_N 21

/* G(u) = erfc(a)*a*exp(a^2) with u = 1/a^2, a in [1, 2].
   degree 30 on [0.25, 1], in the centred
   variable v = (x - MID) * INVHALF; worst relative fit error 6.400E-22 */
#define NL_ERFC_A_MID     0x1.4000000000000p-1
#define NL_ERFC_A_INVHALF 0x1.5555555555555p+1
static const double NL_ERFC_A[31] = {
    0x1.d86d4ee6c550bp-2,   /* v^0 */
    -0x1.4518b9cbfc870p-5,   /* v^1 */
    0x1.ddc55dc4b4f92p-8,   /* v^2 */
    -0x1.caf7497ae34f8p-10,   /* v^3 */
    0x1.fe996058c53acp-12,   /* v^4 */
    -0x1.386ab9c2c450ep-13,   /* v^5 */
    0x1.9934239d00dc0p-15,   /* v^6 */
    -0x1.1a261f720f894p-16,   /* v^7 */
    0x1.953e20b5b2412p-18,   /* v^8 */
    -0x1.2cd40a6592388p-19,   /* v^9 */
    0x1.cb295a9fb6fbfp-21,   /* v^10 */
    -0x1.66c130746c5cbp-22,   /* v^11 */
    0x1.1e0e27f807adfp-23,   /* v^12 */
    -0x1.d05aad2b7d5c6p-25,   /* v^13 */
    0x1.7eda7c0447a0ep-26,   /* v^14 */
    -0x1.400b681f9bea7p-27,   /* v^15 */
    0x1.0ef9858e10b55p-28,   /* v^16 */
    -0x1.d17af5feeecffp-30,   /* v^17 */
    0x1.92e92d03bb9d2p-31,   /* v^18 */
    -0x1.5556e614ecda3p-32,   /* v^19 */
    0x1.2c1259fb04122p-33,   /* v^20 */
    -0x1.474f5d66413e8p-34,   /* v^21 */
    0x1.2841a5d0e4c17p-35,   /* v^22 */
    -0x1.1a5561bdecc06p-40,   /* v^23 */
    0x1.7219b892d5b7ap-43,   /* v^24 */
    -0x1.69645ba8badd2p-37,   /* v^25 */
    0x1.563ac1a00a466p-38,   /* v^26 */
    0x1.725657c760e8ap-39,   /* v^27 */
    -0x1.6444bc6848017p-40,   /* v^28 */
    -0x1.c36e3fb339260p-41,   /* v^29 */
    0x1.ada4b4c5a04d5p-42,   /* v^30 */
};

#define NL_ERFC_A_N 31

/* G(u) = erfc(a)*a*exp(a^2) with u = 1/a^2, a in [2, 5].
   degree 24 on [0.04, 0.25], in the centred
   variable v = (x - MID) * INVHALF; worst relative fit error 5.025E-21 */
#define NL_ERFC_B_MID     0x1.28f5c28f5c28fp-3
#define NL_ERFC_B_INVHALF 0x1.30c30c30c30c3p+3
static const double NL_ERFC_B[25] = {
    0x1.0f5983ef3ba25p-1,   /* v^0 */
    -0x1.58c839c912813p-6,   /* v^1 */
    0x1.15a238f03fe5ap-9,   /* v^2 */
    -0x1.447827e45b2e1p-12,   /* v^3 */
    0x1.d7f2b97329a4ep-15,   /* v^4 */
    -0x1.8e435c6d4135dp-17,   /* v^5 */
    0x1.7702688bc960cp-19,   /* v^6 */
    -0x1.80795e6af8ecep-21,   /* v^7 */
    0x1.a622ad6bbe64ap-23,   /* v^8 */
    -0x1.ea8790ac7e20dp-25,   /* v^9 */
    0x1.2afef1eb53d0ap-26,   /* v^10 */
    -0x1.7bd582b4a3ba1p-28,   /* v^11 */
    0x1.f429d325f78bcp-30,   /* v^12 */
    -0x1.53c5391a1a75bp-31,   /* v^13 */
    0x1.daf1f8fc08205p-33,   /* v^14 */
    -0x1.569e24d978dc3p-34,   /* v^15 */
    0x1.f724980fbfbd4p-36,   /* v^16 */
    -0x1.5fabd76abf987p-37,   /* v^17 */
    0x1.09f3583787341p-38,   /* v^18 */
    -0x1.31046ee2a96b4p-39,   /* v^19 */
    0x1.ef32cb27fd716p-41,   /* v^20 */
    0x1.84c271ce52a14p-44,   /* v^21 */
    -0x1.92c44e173045fp-45,   /* v^22 */
    -0x1.3d05434a365d0p-43,   /* v^23 */
    0x1.0fa666a711d22p-44,   /* v^24 */
};

#define NL_ERFC_B_N 25

/* G(u) = erfc(a)*a*exp(a^2) with u = 1/a^2, a in [5, 27.5].
   degree 16 on [0.00132231, 0.04], in the centred
   variable v = (x - MID) * INVHALF; worst relative fit error 5.923E-23 */
#define NL_ERFC_C_MID     0x1.52832c6e043b4p-6
#define NL_ERFC_C_INVHALF 0x1.9dacdacdacdadp+5
static const double NL_ERFC_C[17] = {
    0x1.1df80ce5cdeadp-1,   /* v^0 */
    -0x1.50ee9a988eadfp-8,   /* v^1 */
    0x1.1ee69dd4f03bap-13,   /* v^2 */
    -0x1.89167127bcc5fp-18,   /* v^3 */
    0x1.6c94c180e951ep-22,   /* v^4 */
    -0x1.a510efd76057fp-26,   /* v^5 */
    0x1.20396098e3cb2p-29,   /* v^6 */
    -0x1.c4d54bbe9f265p-33,   /* v^7 */
    0x1.8f087d28140b7p-36,   /* v^8 */
    -0x1.83d3e1a34c549p-39,   /* v^9 */
    0x1.9a642ea578ebap-42,   /* v^10 */
    -0x1.d41988f0b71a4p-45,   /* v^11 */
    0x1.1d4780761a6bcp-47,   /* v^12 */
    -0x1.6d6781405edbap-50,   /* v^13 */
    0x1.f1fe4d5cf86c2p-53,   /* v^14 */
    -0x1.a855480fbdb12p-55,   /* v^15 */
    0x1.42b5b5d946646p-57,   /* v^16 */
};

#define NL_ERFC_C_N 17

/* Range boundaries in u, so the branch and the fits cannot drift. */
#define NL_ERFC_U0  0x1.0000000000000p+0   /* a = 1 */
#define NL_ERFC_U1  0x1.0000000000000p-2   /* a = 2 */
#define NL_ERFC_U2  0x1.47ae147ae147bp-5   /* a = 5 */

/* The leading 1536 bits of 2/pi, 64 at a time, most significant
   first — word 0 is bits 1..64 of the fraction (2/pi < 1).
   Reducing a double mod pi/2 needs the bits of 2/pi that line up
   with the argument's own exponent, and the largest double has
   exponent 1023, so 24 words covers every finite input with room
   for the 53-bit mantissa and the guard bits the rounding needs. */
static const unsigned long long NL_TWO_OVER_PI[24] = {
    0xA2F9836E4E441529ULL,
    0xFC2757D1F534DDC0ULL,
    0xDB6295993C439041ULL,
    0xFE5163ABDEBBC561ULL,
    0xB7246E3A424DD2E0ULL,
    0x06492EEA09D1921CULL,
    0xFE1DEB1CB129A73EULL,
    0xE88235F52EBB4484ULL,
    0xE99C7026B45F7E41ULL,
    0x3991D639835339F4ULL,
    0x9C845F8BBDF9283BULL,
    0x1FF897FFDE05980FULL,
    0xEF2F118B5A0A6D1FULL,
    0x6D367ECF27CB09B7ULL,
    0x4F463F669E5FEA2DULL,
    0x7527BAC7EBE5F17BULL,
    0x3D0739F78A5292EAULL,
    0x6BFB5FB11F8D5D08ULL,
    0x56033046FC7B6BABULL,
    0xF0CFBC209AF4361DULL,
    0xA9E391615EE61B08ULL,
    0x6599855F14A06840ULL,
    0x8DFFD8804D732731ULL,
    0x06061556CA73A8C9ULL,
};

/* pi/2 split so that k*PIO2_1 is EXACT for every k a Cody-Waite
   reduction can produce: the first three parts carry 24 significant
   bits each and the fourth is the remainder. Without the split the
   reduction loses exactly the bits it exists to preserve. */
#define NL_PIO2_0  0x1.921fb40000000p+0
#define NL_PIO2_1  0x1.4442d00000000p-24
#define NL_PIO2_2  0x1.8469880000000p-48
#define NL_PIO2_3  0x1.8cc51701b839ap-72

#endif /* NURL_NOLIBC_MATH_TABLES_H */
