#!/usr/bin/env python3
# tools/fuzz/report.py — render FUZZRESULTS.md from fuzzer run summaries.
#
# Inputs:
#   * one or more run-summary JSON files (written by fuzz.sh /
#     fuzz_parsers.py via FUZZ_SUMMARY / --summary)
#   * tools/fuzz/FINDINGS.json — the curated findings log
#
# Output: FUZZRESULTS.md at the repo root — committed by the fuzz
# workflow after every run, exactly like bench.yml commits bench/RESULTS.md,
# so the repository always carries the latest fuzzing evidence.
#
# Usage:  report.py [--out FUZZRESULTS.md] summary1.json [summary2.json ...]

import argparse
import datetime
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

FAMILY_DESC = {
    "differential-int":
        "`gen.py` — random integer/float expression trees with a Python "
        "oracle; compiled at `-O0` and `-O2`, both outputs must equal the "
        "oracle bit for bit",
    "differential-struct":
        "`genprog.py` — whole structural programs (enums with N-ary mixed "
        "payloads, match guards/or-patterns/literal constraints, struct "
        "field writes, closures, while/foreach, defer, `% Drop`, "
        "string/Vec/slice ownership, helper calls, recursion) with a "
        "statement-level oracle; `-O0` vs `-O2` vs oracle, plus an "
        "ASan+LSan leg on sampled seeds",
    "parser-mutational":
        "`fuzz_parsers.py` — mutated inputs for the untrusted-input "
        "parsers (x509/DER, cbor, msgpack, json, yaml, xml, toml) against "
        "an ASan+UBSan harness; any crash / OOB / UB / hang is a finding",
}


def sh(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True,
                          cwd=ROOT).stdout.strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "FUZZRESULTS.md"))
    ap.add_argument("summaries", nargs="*")
    args = ap.parse_args()

    runs = []
    for p in args.summaries:
        try:
            with open(p) as fh:
                runs.append(json.load(fh))
        except (OSError, ValueError) as e:
            print(f"report.py: skipping {p}: {e}", file=sys.stderr)

    with open(os.path.join(ROOT, "tools/fuzz/FINDINGS.json")) as fh:
        findings_log = json.load(fh)["findings"]

    commit = sh("git rev-parse --short HEAD") or "unknown"
    version = sh("git describe --tags --always") or commit
    today = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")

    total_findings = sum(r.get("findings", 0) + r.get("buildfail", 0) for r in runs)
    status = "✅ **clean** — no findings" if total_findings == 0 else \
        f"❌ **{total_findings} finding(s)** — reproducers in `tools/fuzz/failures/` (workflow artifact)"

    lines = []
    a = lines.append
    a("# NURL fuzzing results")
    a("")
    a("> AUTO-GENERATED by `tools/fuzz/report.py` — refreshed and committed by")
    a("> [`fuzz.yml`](.github/workflows/fuzz.yml) after every scheduled/manual run,")
    a("> the same way `bench.yml` commits the benchmark numbers. Do not edit by hand;")
    a("> curate the findings log in [`tools/fuzz/FINDINGS.json`](tools/fuzz/FINDINGS.json).")
    a("")
    a(f"_Last run: **{today}** · toolchain `{version}` · commit `{commit}`_")
    a("")
    a(f"**Latest run:** {status}")
    a("")
    a("| family | configuration | executions | pass | findings | sanitized runs |")
    a("|---|---|---:|---:|---:|---:|")
    for r in runs:
        fam = r.get("family", "?")
        if fam.startswith("parser"):
            cfg = f"iters={r.get('size')} rng-seed={r.get('seed_start')}"
            execs = r.get("size", 0)
        else:
            cfg = (f"seeds {r.get('seed_start')}–"
                   f"{r.get('seed_start', 1) + r.get('seed_count', 0) - 1}, "
                   f"size={r.get('size')}, depth={r.get('depth')}")
            execs = r.get("seed_count", 0)
        bad = r.get("findings", 0) + r.get("buildfail", 0)
        a(f"| `{fam}` | {cfg} | {execs} | {r.get('pass', 0)} | {bad} | {r.get('san_runs', 0)} |")
    a("")
    a("## What each family probes")
    a("")
    for fam, desc in FAMILY_DESC.items():
        a(f"- **`{fam}`** — {desc}.")
    a("")
    a("A **finding** is any of: output divergence from the oracle at either")
    a("opt level, a build failure on a generated (always-valid) program, a")
    a("nonzero exit, a hang, or an ASan/LSan/UBSan report. Reproducers are")
    a("uploaded as workflow artifacts and land in `tools/fuzz/failures/`.")
    a("")
    a("## Findings log — real bugs the fuzzers have caught")
    a("")
    a("| date | family | severity | finding | status |")
    a("|---|---|---|---|---|")
    for f in findings_log:
        a(f"| {f['date']} | `{f['family']}` | {f['severity']} | {f['title']} | {f['status']} |")
    a("")
    a("## Running locally")
    a("")
    a("```bash")
    a("./build.sh --no-tests")
    a("tools/fuzz/fuzz.sh 1 500                        # integer differential")
    a("FUZZ_GEN=struct FUZZ_SAN_EVERY=5 \\")
    a("    tools/fuzz/fuzz.sh 1 300 14 3               # structural + sanitizer leg")
    a("tools/fuzz/fuzz_parsers.sh 1 4000 8             # parser mutational")
    a("```")
    a("")

    with open(args.out, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {args.out} ({len(runs)} run summaries, {len(findings_log)} log entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
