// Generated by tools/gen-contributors.mjs --webdocs. Kept in git as the
// fallback when GitHub's contributor API is unavailable during a build.
export const contributors = [
  {
    "name": "Hindurable",
    "login": "Hindurable"
  },
  {
    "name": "iljasrb",
    "login": "iljasrb"
  }
] as const;
