// Generated by tools/gen-site-facts.sh. Kept in git as the
// fallback when the registry stats API is unavailable during a build.
export const releaseFacts = [
  ['31,879', 'lines of NURL in the compiler'],
  ['993', 'compiler test programs'],
  ['231', 'stdlib modules'],
  ['11', 'tested targets'],
  ['60', 'registry packages'],
] as const;
