// Generated by tools/gen-site-facts.sh. Kept in git as the
// fallback when the registry stats API is unavailable during a build.
export const releaseFacts = [
  ['33,795', 'lines of NURL in the compiler'],
  ['1,092', 'compiler test programs'],
  ['232', 'stdlib modules'],
  ['11', 'tested targets'],
  ['62', 'registry packages'],
] as const;
