// Generated by tools/gen-site-facts.sh. Kept in git as the
// fallback when the registry stats API is unavailable during a build.
export const releaseFacts = [
  ['47,268', 'lines of NURL in the compiler'],
  ['1,225', 'compiler test programs'],
  ['233', 'stdlib modules'],
  ['11', 'tested targets'],
  ['64', 'registry packages'],
] as const;
