#!/usr/bin/env python3
"""
bench/token_efficiency.py — BPE-tokeniser-aware token-count comparison
for every cross-language benchmark in this directory.

Counts source tokens with three BPE encoders (cl100k for Claude /
GPT-3.5 / GPT-4 legacy, o200k for GPT-4o / o-series, gpt2 as a
small-vocab proxy for the LLaMA-3 tokeniser, which requires
HuggingFace auth).

Usage:
    python3 bench/token_efficiency.py            # markdown table to stdout
    python3 bench/token_efficiency.py --format=json

Requires:
    pip install tiktoken

The table covers, per benchmark, the three encoders × four languages.
"NURL/Python" is the ratio of NURL's token count to Python's. Numbers
below 1.0 mean NURL took fewer tokens; numbers above 1.0 mean NURL
took more.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import tiktoken
except ImportError:
    sys.stderr.write(
        "tiktoken not installed; run `pip install tiktoken` (or use a venv).\n"
    )
    sys.exit(2)


HERE = Path(__file__).resolve().parent

# (benchmark, language, source-file) tuples. Order is stable so the
# Markdown rendering below comes out reproducibly.
BENCHES = [
    "lcg",
    "sieve",
    "json_parse",
    "fib",
    "collatz",
    "matmul",
    "quicksort",
    "rot13",
]
LANGS = [
    ("NURL", ".nu"),
    ("Python", ".py"),
    ("Rust", ".rs"),
    ("Node", ".js"),
]

# Encoder labels + the bundled-tiktoken name. cl100k is the Claude legacy
# / GPT-3.5 / GPT-4 tokeniser; o200k is the o-series / GPT-4o tokeniser.
# gpt2 is the BPE all the LLaMA derivatives share their byte-pair shape
# with at this granularity; the real Llama-3 tokeniser is HF-gated.
ENCODERS = [
    ("cl100k", "cl100k_base"),
    ("o200k", "o200k_base"),
    ("gpt2", "gpt2"),
]


@dataclass
class Cell:
    enc: str
    bench: str
    lang: str
    tokens: int
    bytes_: int


def read_source(bench: str, ext: str) -> str | None:
    p = HERE / f"{bench}{ext}"
    if not p.exists():
        return None
    return p.read_text(encoding="utf-8")


def count_tokens(text: str, encoder: tiktoken.Encoding) -> int:
    # `encode_ordinary` skips special-token handling — the source files
    # contain literal `<|...|>`-style sequences inside strings (HTTP
    # bodies etc.) in some bench inputs; we want to count every byte
    # as data, not interpret control sequences.
    return len(encoder.encode_ordinary(text))


def collect() -> list[Cell]:
    rows: list[Cell] = []
    for enc_label, enc_name in ENCODERS:
        encoder = tiktoken.get_encoding(enc_name)
        for bench in BENCHES:
            for lang_label, ext in LANGS:
                src = read_source(bench, ext)
                if src is None:
                    continue
                rows.append(
                    Cell(
                        enc=enc_label,
                        bench=bench,
                        lang=lang_label,
                        tokens=count_tokens(src, encoder),
                        bytes_=len(src.encode("utf-8")),
                    )
                )
    return rows


def render_md(rows: Iterable[Cell]) -> str:
    by_enc: dict[str, list[Cell]] = {}
    for r in rows:
        by_enc.setdefault(r.enc, []).append(r)

    out: list[str] = []
    out.append("# Tokeniser-aware token efficiency")
    out.append("")
    out.append(
        "> Generated by `bench/token_efficiency.py`. Lower is better. Every "
        "benchmark computes a byte-identical result in all four languages "
        "(gated by `bench/verify.sh`), so these are genuinely matched "
        "programs, not loose translations."
    )
    out.append("")
    out.append("## Headline (the honest result)")
    out.append("")
    out.append(
        "**On today's production tokenisers, NURL is *not* more "
        "token-efficient than Python — it is substantially less so.** Across "
        "8 matched algorithmic benchmarks NURL costs a **median ~1.7× the "
        "tokens of Python** (cl100k/o200k/gpt2 all agree) and wins on only "
        "**1 of 8** (`lcg`, a four-line arithmetic loop). It is usually the "
        "*most* token-heavy of the four languages — heavier than Rust on most "
        "rows."
    )
    out.append("")
    out.append(
        "The cause is **out-of-distribution fragmentation**, not verbosity "
        "alone. Every public BPE was trained on Python/Rust/JS corpora, so "
        "`def `, `for i in range`, `let mut`, `+=`, `=>` are pre-merged into "
        "one token each, while NURL's glyph-and-prefix surface (`@`, `→`, "
        "`^`, `~`, `: ~ i`, `??`, `*i`) has never been seen and decomposes to "
        "near-character granularity. Note the bytes-on-disk table below: on "
        "several benches NURL is *fewer characters* than Python yet *more "
        "tokens* — character-count was the wrong proxy all along."
    )
    out.append("")
    out.append(
        "**Implication for the project copy:** the raw token-count claim does "
        "not survive measurement and should be dropped. The defensible "
        "LLM-native arguments are (a) grammar *regularity* — a one-page LL(k≤4) "
        "grammar with local semantics — and (b) *first-pass compile success*, "
        "which this study does not measure. See `bench/RESULTS.md` and the "
        "ROADMAP's \"generation-accuracy comparison\" item."
    )
    out.append("")
    out.append("Encoders used:")
    out.append("")
    out.append("* **`cl100k`** — `cl100k_base`. The tokeniser GPT-3.5 / GPT-4 / Claude legacy use.")
    out.append("* **`o200k`** — `o200k_base`. GPT-4o and the o-series.")
    out.append(
        "* **`gpt2`** — the smaller BPE that LLaMA derivatives share their "
        "byte-pair shape with at this granularity. Llama 3's own "
        "tokeniser is HF-gated; gpt2 is used as a proxy."
    )
    out.append("")
    out.append("All counts use `encode_ordinary` — special-token sequences inside string literals stay literal data.")
    out.append("")

    import statistics

    for enc_label, _ in ENCODERS:
        cells = by_enc.get(enc_label, [])
        out.append(f"## `{enc_label}` tokens per benchmark")
        out.append("")
        out.append("| bench | NURL | Python | Rust | Node | NURL/Python |")
        out.append("|-------|-----:|-------:|-----:|-----:|------------:|")
        ratios: list[float] = []
        for bench in BENCHES:
            row = {c.lang: c.tokens for c in cells if c.bench == bench}
            nurl = row.get("NURL")
            py = row.get("Python")
            rs = row.get("Rust")
            js = row.get("Node")
            ratio = ""
            if nurl is not None and py is not None and py > 0:
                r = nurl / py
                ratios.append(r)
                ratio = f"{r:.2f}×"
            out.append(
                "| `{b}` | {nurl} | {py} | {rs} | {js} | {ratio} |".format(
                    b=bench,
                    nurl="—" if nurl is None else nurl,
                    py="—" if py is None else py,
                    rs="—" if rs is None else rs,
                    js="—" if js is None else js,
                    ratio=ratio,
                )
            )
        if ratios:
            wins = sum(1 for r in ratios if r < 1.0)
            out.append(
                "| **summary** | | | | | **median {med:.2f}× · "
                "NURL fewer tokens than Python in {wins}/{n}** |".format(
                    med=statistics.median(ratios), wins=wins, n=len(ratios)
                )
            )
        out.append("")

    # Bytes-on-disk reference table.
    out.append("## Source size (bytes on disk, reference)")
    out.append("")
    out.append("| bench | NURL | Python | Rust | Node |")
    out.append("|-------|-----:|-------:|-----:|-----:|")
    sizes: dict[tuple[str, str], int] = {}
    for c in rows:
        sizes[(c.bench, c.lang)] = c.bytes_
    for bench in BENCHES:
        out.append(
            "| `{b}` | {n} | {p} | {r} | {j} |".format(
                b=bench,
                n=sizes.get((bench, "NURL"), "—"),
                p=sizes.get((bench, "Python"), "—"),
                r=sizes.get((bench, "Rust"), "—"),
                j=sizes.get((bench, "Node"), "—"),
            )
        )
    out.append("")

    out.append("## Notes on interpretation")
    out.append("")
    out.append(
        "**The out-of-distribution penalty is the whole story.** These "
        "tokenisers were trained on Python / Rust / JS corpora, so their BPE "
        "merges common multi-character sequences in those languages into "
        "single tokens (`def `, `function `, `for i in range`, `let mut`, "
        "`=>`). NURL source is in none of these corpora, so its keyword- and "
        "glyph-shaped tokens decompose to near-character granularity. That is "
        "a property of the *training corpus*, not of the grammar's "
        "regularity — a tokeniser that had seen NURL would compress it far "
        "better (testing that is a separate, \"what-could-be\" experiment "
        "and is deliberately out of scope here)."
    )
    out.append("")
    out.append(
        "**This does not mean NURL has no LLM-native advantage — it means the "
        "advantage is not raw token count.** Two claims are tangled in the "
        "project copy and must be separated: (1) \"fewer tokens on today's "
        "tokenisers\" — refuted here; (2) \"a regular, locally-decodable "
        "grammar is easier for a model to generate *correctly*\" — untested by "
        "this study and the more honest banner to fly. The next step the "
        "ROADMAP already lists is a controlled first-pass-compile-success "
        "comparison."
    )
    out.append("")
    out.append(
        "**Caveat on the corpus.** These are eight small, arithmetic- and "
        "systems-leaning micro-benchmarks, a regime that rewards terse infix "
        "math and penalises NURL's explicit prefix/type surface. They are not "
        "a representative sample of all agent-written code (no parsers, web "
        "handlers, glue, or data plumbing). They are, however, enough to "
        "retire the unqualified \"more token-efficient\" claim."
    )
    out.append("")
    out.append(
        "The Rust column for `json_parse` (1140–2065 tokens) reflects Serde "
        "derive macros and explicit type signatures that other languages do "
        "not require for the same task — a reminder that token count is "
        "task- and style-dependent in every language."
    )
    out.append("")
    return "\n".join(out)


def render_json(rows: Iterable[Cell]) -> str:
    return json.dumps(
        [
            {
                "encoder": r.enc,
                "bench": r.bench,
                "language": r.lang,
                "tokens": r.tokens,
                "bytes": r.bytes_,
            }
            for r in rows
        ],
        indent=2,
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--format", choices=("md", "json"), default="md")
    args = ap.parse_args()
    rows = collect()
    out = render_md(rows) if args.format == "md" else render_json(rows)
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
