#!/usr/bin/env python3
"""
bench/token_efficiency.py — BPE-tokeniser-aware token-count comparison
for every cross-language benchmark in this directory.

Counts source tokens with three BPE encoders (cl100k for Claude /
GPT-3.5 / GPT-4 legacy, o200k for GPT-4o / o-series, gpt2 as a
small-vocab proxy for the LLaMA-3 tokeniser, which requires
HuggingFace auth).

Usage:
    python3 bench/token_efficiency.py            # markdown table to stdout
    python3 bench/token_efficiency.py --format=json

Requires:
    pip install tiktoken

The table covers, per benchmark, the three encoders × four languages.
"NURL/Python" is the ratio of NURL's token count to Python's. Numbers
below 1.0 mean NURL took fewer tokens; numbers above 1.0 mean NURL
took more.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import tiktoken
except ImportError:
    sys.stderr.write(
        "tiktoken not installed; run `pip install tiktoken` (or use a venv).\n"
    )
    sys.exit(2)


HERE = Path(__file__).resolve().parent

# (benchmark, language, source-file) tuples. Order is stable so the
# Markdown rendering below comes out reproducibly.
BENCHES = ["lcg", "sieve", "json_parse"]
LANGS = [
    ("NURL", ".nu"),
    ("Python", ".py"),
    ("Rust", ".rs"),
    ("Node", ".js"),
]

# Encoder labels + the bundled-tiktoken name. cl100k is the Claude legacy
# / GPT-3.5 / GPT-4 tokeniser; o200k is the o-series / GPT-4o tokeniser.
# gpt2 is the BPE all the LLaMA derivatives share their byte-pair shape
# with at this granularity; the real Llama-3 tokeniser is HF-gated.
ENCODERS = [
    ("cl100k", "cl100k_base"),
    ("o200k", "o200k_base"),
    ("gpt2", "gpt2"),
]


@dataclass
class Cell:
    enc: str
    bench: str
    lang: str
    tokens: int
    bytes_: int


def read_source(bench: str, ext: str) -> str | None:
    p = HERE / f"{bench}{ext}"
    if not p.exists():
        return None
    return p.read_text(encoding="utf-8")


def count_tokens(text: str, encoder: tiktoken.Encoding) -> int:
    # `encode_ordinary` skips special-token handling — the source files
    # contain literal `<|...|>`-style sequences inside strings (HTTP
    # bodies etc.) in some bench inputs; we want to count every byte
    # as data, not interpret control sequences.
    return len(encoder.encode_ordinary(text))


def collect() -> list[Cell]:
    rows: list[Cell] = []
    for enc_label, enc_name in ENCODERS:
        encoder = tiktoken.get_encoding(enc_name)
        for bench in BENCHES:
            for lang_label, ext in LANGS:
                src = read_source(bench, ext)
                if src is None:
                    continue
                rows.append(
                    Cell(
                        enc=enc_label,
                        bench=bench,
                        lang=lang_label,
                        tokens=count_tokens(src, encoder),
                        bytes_=len(src.encode("utf-8")),
                    )
                )
    return rows


def render_md(rows: Iterable[Cell]) -> str:
    by_enc: dict[str, list[Cell]] = {}
    for r in rows:
        by_enc.setdefault(r.enc, []).append(r)

    out: list[str] = []
    out.append("# Tokeniser-aware token efficiency")
    out.append("")
    out.append(
        "> Generated by `bench/token_efficiency.py`. Lower is better."
    )
    out.append("")
    out.append("Encoders used:")
    out.append("")
    out.append("* **`cl100k`** — `cl100k_base`. The tokeniser GPT-3.5 / GPT-4 / Claude legacy use.")
    out.append("* **`o200k`** — `o200k_base`. GPT-4o and the o-series.")
    out.append(
        "* **`gpt2`** — the smaller BPE that LLaMA derivatives share their "
        "byte-pair shape with at this granularity. Llama 3's own "
        "tokeniser is HF-gated; gpt2 is used as a proxy."
    )
    out.append("")
    out.append("All counts use `encode_ordinary` — special-token sequences inside string literals stay literal data.")
    out.append("")

    for enc_label, _ in ENCODERS:
        cells = by_enc.get(enc_label, [])
        out.append(f"## `{enc_label}` tokens per benchmark")
        out.append("")
        out.append("| bench | NURL | Python | Rust | Node | NURL/Python |")
        out.append("|-------|-----:|-------:|-----:|-----:|------------:|")
        for bench in BENCHES:
            row = {c.lang: c.tokens for c in cells if c.bench == bench}
            nurl = row.get("NURL")
            py = row.get("Python")
            rs = row.get("Rust")
            js = row.get("Node")
            ratio = ""
            if nurl is not None and py is not None and py > 0:
                ratio = f"{nurl / py:.2f}×"
            out.append(
                "| `{b}` | {nurl} | {py} | {rs} | {js} | {ratio} |".format(
                    b=bench,
                    nurl="—" if nurl is None else nurl,
                    py="—" if py is None else py,
                    rs="—" if rs is None else rs,
                    js="—" if js is None else js,
                    ratio=ratio,
                )
            )
        out.append("")

    # Bytes-on-disk reference table.
    out.append("## Source size (bytes on disk, reference)")
    out.append("")
    out.append("| bench | NURL | Python | Rust | Node |")
    out.append("|-------|-----:|-------:|-----:|-----:|")
    sizes: dict[tuple[str, str], int] = {}
    for c in rows:
        sizes[(c.bench, c.lang)] = c.bytes_
    for bench in BENCHES:
        out.append(
            "| `{b}` | {n} | {p} | {r} | {j} |".format(
                b=bench,
                n=sizes.get((bench, "NURL"), "—"),
                p=sizes.get((bench, "Python"), "—"),
                r=sizes.get((bench, "Rust"), "—"),
                j=sizes.get((bench, "Node"), "—"),
            )
        )
    out.append("")

    out.append("## Notes on interpretation")
    out.append("")
    out.append(
        "These tokenisers were trained on Python / Rust / JS corpora. "
        "Their BPE merges common multi-character sequences in those "
        "languages into single tokens (`def `, `function `, `for i in "
        "range`, `let mut`, `=>`). NURL source is not in any of these "
        "corpora, so NURL keyword-shaped tokens decompose to individual "
        "character pairs."
    )
    out.append("")
    out.append(
        "The Rust column for `json_parse` (1140–2065 tokens) reflects "
        "Serde derive macros and explicit type signatures that other "
        "languages do not require for the same task."
    )
    out.append("")
    return "\n".join(out)


def render_json(rows: Iterable[Cell]) -> str:
    return json.dumps(
        [
            {
                "encoder": r.enc,
                "bench": r.bench,
                "language": r.lang,
                "tokens": r.tokens,
                "bytes": r.bytes_,
            }
            for r in rows
        ],
        indent=2,
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--format", choices=("md", "json"), default="md")
    args = ap.parse_args()
    rows = collect()
    out = render_md(rows) if args.format == "md" else render_json(rows)
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
