#!/usr/bin/env python3
# Regenerate src/page_data.nu from views/index.html.
#
# The test page is a runtime asset, but `nurlpkg install` ships only the
# built binary — a relative views/ path can never resolve for an installed
# tool. Same pattern (and same reasons) as packages/yoloe-demo's embedder:
# ~32 KB line-aligned chunks because released nurlc (<= v0.11.1)
# stack-overflows past ~48 KB per string literal, and a registry package
# must build with the toolchain users have.
import pathlib

CHUNK = 32 * 1024

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "views" / "index.html").read_text(encoding="utf-8")
assert "`" not in src, "index.html must not contain backticks (NURL literal delimiter)"

chunks, pos = [], 0
while pos < len(src):
    end = min(pos + CHUNK, len(src))
    if end < len(src):
        nl = src.rfind("\n", pos, end)
        assert nl > pos, "line longer than a chunk?"
        end = nl + 1
    chunks.append(src[pos:end].replace("\\", "\\\\"))
    pos = end

arms = "".join(
    "    ? == k %d { ^ `%s` } {}\n" % (i, c) for i, c in enumerate(chunks)
)
out = root / "src" / "page_data.nu"
out.write_text(
    "// GENERATED by tools/embed_page.py from views/index.html — do not edit.\n"
    "// The built-in test page, embedded so installed binaries need no views/\n"
    "// directory on disk. Chunked: released nurlc (<= v0.11.1) stack-overflows\n"
    "// on literals past ~48 KB.\n"
    "\n"
    "@ wh_page_chunks → i {\n"
    "    ^ %d\n"
    "}\n"
    "\n"
    "@ wh_page_chunk i k → s {\n%s    ^ ``\n}\n" % (len(chunks), arms),
    encoding="utf-8",
)
print(f"wrote src/page_data.nu: {len(chunks)} chunk(s), {len(src)} bytes")
