#!/usr/bin/env bash
# ============================================================
#  unikernel/compile_nu.sh — compile one NURL program for a
#  freestanding link, pulling in the NURL socket layer if (and only if)
#  the program actually needs it.
#
#  Usage:  compile_nu.sh <src.nu> <out.ll> <workdir>
#
#  A hosted program gets its sockets from stdlib/runtime_ffi.c, which is
#  the one file a freestanding target cannot have. unikernel/net/
#  sockets.nu defines the same symbols in NURL over the sans-IO stack,
#  and nurlc lets a definition supersede an FFI declaration — so the
#  program is unchanged and only the link line differs.
#
#  It cannot simply be a separate object: NURL compiles a program and
#  its imports into ONE module, so a separately-built shim would carry
#  its own copy of every stdlib function it uses and the link would die
#  of duplicate definitions. It has to be part of the same compilation,
#  which is what the generated root file below does — it imports the
#  program and the shim, and `main` comes from the program.
#
#  Whether it is needed is MEASURED, not listed: the program is compiled
#  once on its own, its undefined symbols are read out of the object
#  with `nm`, and the set the shim defines is grepped out of the shim's
#  own source. Neither side is a list in this file — a hand-kept list of
#  names is what gated the whole live surface of the runtime out of CI,
#  twice.
#
#  Exit status is nurlc's / clang's. The object is left at
#  <workdir>/<name>.o next to the .ll.
# ============================================================
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHIM="$ROOT/unikernel/net/sockets.nu"
CC="${CC:-clang}"

SRC="$1"; OUT_LL="$2"; WORK="$3"
name="$(basename "${OUT_LL%.ll}")"
OBJ="$WORK/$name.o"

cd "$ROOT" || exit 2

"$ROOT/build/nurlc" "$SRC" > "$OUT_LL" 2>"$WORK/compile.err" || exit 3
"$CC" -O2 -c "$OUT_LL" -o "$OBJ" 2>"$WORK/cc.err" || exit 4

# What does the shim define? Its own `@ nurl_*` definitions, read from
# the file that defines them.
shim_syms=$(grep -oE '^@ nurl_[A-Za-z0-9_]+' "$SHIM" | awk '{print $2}' | sort -u)
[ -n "$shim_syms" ] || exit 0

undef=$(nm -u "$OBJ" 2>/dev/null | awk '{print $NF}' | sort -u)
need=$(comm -12 <(printf '%s\n' "$undef") <(printf '%s\n' "$shim_syms"))
[ -n "$need" ] || exit 0

# Needed. Recompile through a root that imports both.
root_nu="$WORK/__with_sockets.nu"
{
    echo "// generated by unikernel/compile_nu.sh — do not edit"
    echo "// $name needs:$(printf ' %s' $need)"
    printf '$ `%s`\n' "$(cd "$(dirname "$SRC")" && pwd)/$(basename "$SRC")"
    printf '$ `%s`\n' "$SHIM"
} > "$root_nu"

"$ROOT/build/nurlc" "$root_nu" > "$OUT_LL" 2>"$WORK/compile.err" || exit 3
"$CC" -O2 -c "$OUT_LL" -o "$OBJ" 2>"$WORK/cc.err" || exit 4
exit 0
