#!/bin/sh
# ============================================================
#  packages/onnx — static-backend end-to-end test
#
#  The gpu package's STATIC backend (no NVRTC, no host compiler, no
#  dlopen — what every wasm build runs on) links a kernel set generated by
#  tools/gen_static_kernels.nu. Up to 0.9.0 that generator imported a file
#  deleted in 0.7.0 and nothing noticed. tests/census_test.nu proves the
#  generated set covers the executor; this proves the set WORKS:
#
#    1. generate kernels_static.c from the executor's kernel census
#    2. compile it natively (cc -O2) — and for wasm32-wasi when zig is
#       available (NURL_ZIG, ~/.nurl/zig/zig, or zig on PATH)
#    3. link it into the onnx CLI and run tiny.onnx with NURL_GPU=static
#       against the onnxruntime reference — and check the run really was
#       on the static backend
#
#  Run from the package dir:  ./tests/static_test.sh
# ============================================================
set -u
cd "$(dirname "$0")/.."
REPO_ROOT="$(cd ../.. && pwd)"

if [ -n "${NURL:-}" ]; then :;
elif [ -x "$REPO_ROOT/nurl.sh" ]; then NURL="$REPO_ROOT/nurl.sh"; export NURL_STDLIB="${NURL_STDLIB:-$REPO_ROOT}";
else NURL="nurl"; fi
CC="${CC:-cc}"

WORK="$(mktemp -d -t onnxstatic.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

echo "[1/4] generate kernels_static.c"
if ! $NURL tools/gen_static_kernels.nu "$WORK/gen" >/dev/null 2>"$WORK/build.err"; then
    echo "  generator build FAILED"; cat "$WORK/build.err"; exit 1
fi
"$WORK/gen" "$WORK/kernels_static.c" || { echo "  FAIL generator"; exit 1; }

echo "[2/4] compile it (native, and wasm32-wasi when zig is present)"
if ! command -v "$CC" >/dev/null 2>&1; then
    echo "  skip: no C compiler ($CC)"; exit 0
fi
"$CC" -O2 -c "$WORK/kernels_static.c" -o "$WORK/kernels_static.o" \
    || { echo "  FAIL native compile"; exit 1; }
ZIG="${NURL_ZIG:-$HOME/.nurl/zig/zig}"
[ -x "$ZIG" ] || ZIG="$(command -v zig 2>/dev/null || true)"
if [ -n "$ZIG" ] && [ -x "$ZIG" ]; then
    "$ZIG" cc --target=wasm32-wasi -O2 -msimd128 -c "$WORK/kernels_static.c" -o "$WORK/kernels_static.wasm.o" \
        || { echo "  FAIL wasm32-wasi compile"; exit 1; }
    echo "  ok native + wasm32-wasi"
else
    echo "  ok native (no zig: wasm32 compile skipped)"
fi

echo "[3/4] link the CLI with the static kernels"
if ! NURL_EXTRA_OBJS="$WORK/kernels_static.o" $NURL src/main.nu "$WORK/onnx" >/dev/null 2>"$WORK/build.err"; then
    echo "  build FAILED"; cat "$WORK/build.err"; exit 1
fi

echo "[4/4] run tiny.onnx on the static backend against the onnxruntime reference"
OUT=$(NURL_GPU=static "$WORK/onnx" tests/data/tiny.onnx tests/data/tiny.in.f32 tests/data/tiny.out.f32 2>&1)
printf '%s\n' "$OUT" | grep -q "device: CPU (static kernels)" \
    || { echo "  FAIL did not run on the static backend"; printf '%s\n' "$OUT"; exit 1; }
printf '%s\n' "$OUT" | grep -q "MATCH ✓" \
    && echo "  PASS static kernels generate, compile, run and match the reference" \
    || { echo "  FAIL"; printf '%s\n' "$OUT"; exit 1; }
