(module
  (memory 1 2)
  (data (i32.const 8) "ACTIVE")
  (data $p "PASSIVE!")
  (func (export "init") (result i32)
    ;; copy "PASS" to 100, read back first byte
    (memory.init $p (i32.const 100) (i32.const 0) (i32.const 4))
    (i32.load8_u (i32.const 100)))
  (func (export "active0") (result i32)
    ;; passive data must NOT be at offset 0 (regression: it used to be copied there)
    (i32.load8_u (i32.const 0)))
  (func (export "activeb") (result i32)
    (i32.load8_u (i32.const 8)))
  (func (export "drop2") (result i32)
    (data.drop $p)
    (memory.init $p (i32.const 200) (i32.const 0) (i32.const 1))
    (i32.const 0))
  (func (export "grow") (param i32) (result i32)
    (memory.grow (local.get 0)))
  (func (export "size") (result i32) (memory.size)))
