#!/usr/bin/env bash
# ============================================================
#  unikernel/tests/selfhost_gate.sh — the bootstrap fixed point, taken
#  inside a machine with no operating system.
#
#  `build.sh` proves the compiler is a fixed point by having the
#  compiler built from `compiler/nurlc.nu` compile that same source and
#  comparing the IR it emits with the IR it was itself built from:
#  `cmp build/nurlc_self.ll build/nurlc_self2.ll`. This gate is that
#  same equality with the compiler running as wasm, in-process on
#  `packages/wasmtime`, inside a unikernel:
#
#    1. wasmbuilder compiles compiler/nurlc.nu → nurlc.wasm. Native
#       nurlc emits the IR, zig's wasm-ld links it — the one part of
#       the chain that needs a host, because nurlc's backend is LLVM
#       IR and there is no LLVM in the guest.
#    2. the IR native nurlc emits for the SAME source goes into the
#       image beside the module and the source. That IR is not a
#       reference picked for convenience: `$NURLC` below is the binary
#       wasmbuilder itself uses (wb_find_nurlc reads it first), so
#       those bytes are exactly what nurlc.wasm was linked from.
#    3. the guest decodes the module, runs it over `nurlc.nu`, and
#       compares the 4.3 MB it emits BYTE FOR BYTE with that IR.
#
#  Byte-identical therefore says: the compiler, running as wasm with no
#  libc and no kernel under it, reproduces its own build input from its
#  own source. What the guest cannot check is the link — turning that
#  IR back into a module needs LLVM, which stays on the host.
#
#  DELIBERATELY NOT AUTOMATIC: not in run_qemu_tests.sh, not in CI. The
#  guest spends ~22 minutes here under TCG (the wasm interpreter costs
#  ~150x native, TCG another ~12x on top of that), against 23 s for
#  wasmc_gate.sh and its eight small programs. That gate is the one
#  that runs per push; this one is run by hand when the bootstrap or
#  the wasm path changed.
#
#  Needs: zig (NURL_ZIG / $NURL_HOME/zig/zig / PATH) for the wasm link,
#  and QEMU for the guest. Without either it SKIPS loudly.
#
#  Usage: selfhost_gate.sh   (QEMU / QEMU_ARGS honoured via run_qemu.sh)
# ============================================================
set -uo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
say() { echo "selfhost_gate: $*"; }

command -v "${QEMU:-qemu-system-x86_64}" >/dev/null 2>&1 \
    || { say "SKIP: ${QEMU:-qemu-system-x86_64} not found"; exit 0; }
if [ -n "${NURL_ZIG:-}" ] && [ -x "${NURL_ZIG:-}" ]; then :
elif [ -x "${NURL_HOME:-$HOME/.nurl}/zig/zig" ]; then export NURL_ZIG="${NURL_HOME:-$HOME/.nurl}/zig/zig"
elif command -v zig >/dev/null 2>&1; then :
else say "SKIP: no zig — the wasm link needs one (set NURL_ZIG)"; exit 0; fi

OUTDIR="${NURL_UNIKERNEL_OUT:-$ROOT/build/unikernel}"
WORK="$OUTDIR/selfhost"
rm -rf "$WORK"; mkdir -p "$WORK/fs" "$OUTDIR"

# Load-bearing: wasmbuilder resolves nurlc from $NURLC before anything
# else, so step 1 and step 2 below are the same compiler.
export NURLC="${NURLC:-$ROOT/build/nurlc}"
export NURL_STDLIB="${NURL_STDLIB:-$ROOT}"
[ -x "$NURLC" ] || { say "FAIL: no compiler at $NURLC — run ./build.sh"; exit 1; }

# ── 1. the compiler, as wasm ────────────────────────────────────
# wasmbuilder has no dependencies of its own, so this driver imports
# its source directly — there is nothing to materialise first.
cat > "$WORK/mkwasm.nu" <<'EOF'
// generated by unikernel/tests/selfhost_gate.sh — compile one .nu to wasm
$ `stdlib/core/string.nu`
$ `stdlib/core/vec.nu`
$ `stdlib/ext/env.nu`
$ `packages/wasmbuilder/src/build.nu`

@ main → i {
    ? < ( env_args_count ) 3 { ( nurl_print `usage: mkwasm <in.nu> <out.wasm>\n` ) ^ 2 } {}
    : String src ( env_arg 1 )
    : String out ( env_arg 2 )
    : WbOpts o ( wb_opts_default )
    ?? ( wb_build_file ( string_data src ) ( string_data out ) o ) {
        T _ → { ^ 0 }
        F e → { ( nurl_print ( string_data e ) ) ( nurl_print `\n` ) ^ 1 }
    }
}
EOF
if ! ( cd "$ROOT" && "$ROOT/nurl.sh" "$WORK/mkwasm.nu" "$WORK/mkwasm" >"$WORK/mk.log" 2>&1 ); then
    say "FAIL: the wasm build driver did not compile"
    tail -5 "$WORK/mk.log" | sed 's/^/selfhost_gate:   /'
    exit 1
fi
if ! ( cd "$ROOT" && "$WORK/mkwasm" compiler/nurlc.nu "$WORK/fs/nurlc.wasm" >"$WORK/wasm.log" 2>&1 ); then
    say "FAIL: nurlc.nu did not build as wasm"
    tail -5 "$WORK/wasm.log" | sed 's/^/selfhost_gate:   /'
    exit 1
fi
say "nurlc.wasm: $(stat -c%s "$WORK/fs/nurlc.wasm") bytes"

# ── 2. the source, and the IR it was built from ─────────────────
# `compiler/nurlc.nu` has no `$` imports, which is why this fits in an
# image at all: the guest needs the one file, not the stdlib. The IR
# carries no path (only the basename, in a comment), so compiling it
# here and as `nurlc.nu` in the guest is the same compilation.
cp "$ROOT/compiler/nurlc.nu" "$WORK/fs/nurlc.nu"
if ! "$NURLC" "$WORK/fs/nurlc.nu" > "$WORK/fs/nurlc.nu.ll" 2>"$WORK/native.err"; then
    say "FAIL: the NATIVE compiler could not compile nurlc.nu"
    tail -3 "$WORK/native.err" | sed 's/^/selfhost_gate:   /'
    exit 1
fi
say "native IR: $(stat -c%s "$WORK/fs/nurlc.nu.ll") bytes from $(wc -l < "$WORK/fs/nurlc.nu") lines"

# ── 3. the guest ────────────────────────────────────────────────
# The demo takes its programs from argv, so the fixed point needs no
# demo of its own: it is wasmc.nu pointed at one file.
if ! "$ROOT/unikernel/build_unikernel.sh" "$ROOT/unikernel/demos/wasmc.nu" \
        --fs "$WORK/fs" -o "$WORK/selfhost.elf" >"$WORK/img.log" 2>&1; then
    say "FAIL: the guest image did not build"
    tail -6 "$WORK/img.log" | sed 's/^/selfhost_gate:   /'
    exit 1
fi

say "booting — the guest compiles the compiler, ~22 min under TCG"
t0=$(date +%s)
out=$(NURL_APPEND='args="nurlc.nu"' \
      "$ROOT/unikernel/run_qemu.sh" "$WORK/selfhost.elf" -t "${NURL_SELFHOST_TIMEOUT:-2700}" -- -m 1024 2>&1)
rc=$?
took=$(( $(date +%s) - t0 ))

printf '%s\n' "$out" | sed 's/^/selfhost_gate:   /'
if [ "$rc" != 0 ] || ! printf '%s' "$out" | grep -q 'nurlc.nu: byte-identical to native'; then
    say "FAIL: the fixed point does NOT hold in the guest (exit $rc, ${took}s)"
    exit 1
fi
say "verified: nurlc.wasm compiled compiler/nurlc.nu IN THE GUEST to the bytes it was built from (${took}s)"
exit 0
