#!/usr/bin/env bash
# ============================================================
#  unikernel/tests/wasmc_gate.sh — the NURL compiler, as wasm, inside
#  a machine with no operating system, emitting the SAME BYTES as the
#  native compiler.
#
#  What it does, in one line each:
#    1. wasmbuilder compiles compiler/nurlc.nu → nurlc.wasm (locally:
#       native nurlc for the IR, zig's wasm-ld for the link — no
#       container, no network).
#    2. the native compiler emits the IR for a handful of corpus
#       programs; both the programs and that IR go into the image.
#    3. the guest boots, decodes nurlc.wasm on `packages/wasmtime`
#       (in-process — a unikernel has no subprocess to run it in),
#       compiles each program, and compares its output BYTE FOR BYTE
#       with the native IR baked in beside it.
#
#  The corpus is import-free on purpose: a program with `$` imports
#  would need the stdlib inside the image, which says nothing extra
#  about the compiler and costs megabytes. What these eight do cover
#  is the language's own surface — enums and match, closures and
#  capture, unsigned and fixed-width arithmetic, wildcards, a context
#  switch — and every one of them lands on the same bytes.
#
#  Needs: zig (NURL_ZIG / $NURL_HOME/zig/zig / PATH) for the wasm
#  link, and QEMU for the guest. Without either it SKIPS loudly.
#
#  Usage: wasmc_gate.sh     (QEMU / QEMU_ARGS honoured via run_qemu.sh)
# ============================================================
set -uo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
say() { echo "wasmc_gate: $*"; }

command -v "${QEMU:-qemu-system-x86_64}" >/dev/null 2>&1 \
    || { say "SKIP: ${QEMU:-qemu-system-x86_64} not found"; exit 0; }
if [ -n "${NURL_ZIG:-}" ] && [ -x "${NURL_ZIG:-}" ]; then :
elif [ -x "${NURL_HOME:-$HOME/.nurl}/zig/zig" ]; then export NURL_ZIG="${NURL_HOME:-$HOME/.nurl}/zig/zig"
elif command -v zig >/dev/null 2>&1; then :
else say "SKIP: no zig — the wasm link needs one (set NURL_ZIG)"; exit 0; fi

OUTDIR="${NURL_UNIKERNEL_OUT:-$ROOT/build/unikernel}"
WORK="$OUTDIR/wasmc"
rm -rf "$WORK"; mkdir -p "$WORK/fs" "$OUTDIR"

export NURLC="${NURLC:-$ROOT/build/nurlc}"
export NURL_STDLIB="${NURL_STDLIB:-$ROOT}"

# ── 1. the compiler, as wasm ────────────────────────────────────
# wasmbuilder itself has no dependencies, so the driver below imports
# its source directly — nothing to materialise (unlike swarm_gate).
cat > "$WORK/mkwasm.nu" <<'EOF'
// generated by unikernel/tests/wasmc_gate.sh — compile one .nu to wasm
$ `stdlib/core/string.nu`
$ `stdlib/core/vec.nu`
$ `stdlib/ext/env.nu`
$ `packages/wasmbuilder/src/build.nu`

@ main → i {
    ? < ( env_args_count ) 3 { ( nurl_print `usage: mkwasm <in.nu> <out.wasm>\n` ) ^ 2 } {}
    : String src ( env_arg 1 )
    : String out ( env_arg 2 )
    : WbOpts o ( wb_opts_default )
    ?? ( wb_build_file ( string_data src ) ( string_data out ) o ) {
        T _ → { ^ 0 }
        F e → { ( nurl_print ( string_data e ) ) ( nurl_print `\n` ) ^ 1 }
    }
}
EOF
if ! ( cd "$ROOT" && "$ROOT/nurl.sh" "$WORK/mkwasm.nu" "$WORK/mkwasm" >"$WORK/mk.log" 2>&1 ); then
    say "FAIL: the wasm build driver did not compile"
    tail -5 "$WORK/mk.log" | sed 's/^/wasmc_gate:   /'
    exit 1
fi
if ! ( cd "$ROOT" && "$WORK/mkwasm" compiler/nurlc.nu "$WORK/fs/nurlc.wasm" >"$WORK/wasm.log" 2>&1 ); then
    say "FAIL: nurlc.nu did not build as wasm"
    tail -5 "$WORK/wasm.log" | sed 's/^/wasmc_gate:   /'
    exit 1
fi
say "nurlc.wasm: $(stat -c%s "$WORK/fs/nurlc.wasm") bytes"

# ── 2. the corpus, and the native IR to match ───────────────────
# Import-free programs: the image carries no stdlib.
PROGS="hello showcase test_04_enum_variants_and_match test_05_closures_and_capture
       unsigned_arith fixed_size_types ctx_switch wildcard"
args=""
for p in $PROGS; do
    cp "$ROOT/compiler/tests/$p.nu" "$WORK/fs/$p.nu"
    if ! "$NURLC" "$WORK/fs/$p.nu" > "$WORK/fs/$p.nu.ll" 2>"$WORK/native.err"; then
        say "FAIL: the NATIVE compiler could not compile $p.nu"
        tail -3 "$WORK/native.err" | sed 's/^/wasmc_gate:   /'
        exit 1
    fi
    args="$args $p.nu"
done

# ── 3. the guest ────────────────────────────────────────────────
if ! "$ROOT/unikernel/build_unikernel.sh" "$ROOT/unikernel/demos/wasmc.nu" \
        --fs "$WORK/fs" -o "$WORK/wasmc.elf" >"$WORK/img.log" 2>&1; then
    say "FAIL: the guest image did not build"
    tail -6 "$WORK/img.log" | sed 's/^/wasmc_gate:   /'
    exit 1
fi

t0=$(date +%s)
out=$(NURL_APPEND="args=\"${args# }\"" \
      "$ROOT/unikernel/run_qemu.sh" "$WORK/wasmc.elf" -t 900 -- -m 1024 2>&1)
rc=$?
took=$(( $(date +%s) - t0 ))

printf '%s\n' "$out" | sed 's/^/wasmc_gate:   /'
if [ "$rc" != 0 ] || ! printf '%s' "$out" | grep -q 'all byte-identical'; then
    say "FAIL: the wasm compiler did not agree with the native one (exit $rc)"
    exit 1
fi
n=$(printf '%s' "$out" | grep -c 'byte-identical to native')
say "verified: $n programs compiled by nurlc.wasm IN THE GUEST, byte-identical to native (${took}s)"
exit 0
