#!/usr/bin/env bash
# Copyright (c) 2026 The NURL Project Developers
# SPDX-License-Identifier: MIT OR Apache-2.0
# Generate release facts for webdocs' static homepage.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/webdocs/lib/release-facts.generated.ts"
TARGETS="$ROOT/webdocs/site-facts.json"

comma() { sed -E ':a;s/([0-9])([0-9]{3})($|,)/\1,\2\3/;ta' <<< "$1"; }
previous_registry() {
    sed -n "s/^  \['\([^']*\)', 'registry packages'\],$/\1/p" "$OUT" 2>/dev/null | head -1
}

compiler_lines="$(comma "$(wc -l < "$ROOT/compiler/nurlc.nu")")"
tests="$(comma "$(find "$ROOT/compiler/tests" -maxdepth 1 -name '*.nu' | wc -l | tr -d ' ')")"
stdlib_modules="$(find "$ROOT/stdlib" -name '*.nu' | wc -l | tr -d ' ')"
targets="$(node -e 'console.log(require(process.argv[1]).targets.length)' "$TARGETS")"
registry_packages=""
if stats="$(curl -fsS --max-time 8 "${NURL_REGISTRY_URL:-https://reg.nurl-lang.org}/api/v1/stats" 2>/dev/null)"; then
    registry_packages="$(grep -oE '"packages"[[:space:]]*:[[:space:]]*[0-9]+' <<< "$stats" | grep -oE '[0-9]+' | head -1)"
fi
registry_packages="${registry_packages:-$(previous_registry)}"
registry_packages="${registry_packages:-0}"

cat > "$OUT" <<EOF
// Generated by tools/gen-site-facts.sh. Kept in git as the
// fallback when the registry stats API is unavailable during a build.
export const releaseFacts = [
  ['$compiler_lines', 'lines of NURL in the compiler'],
  ['$tests', 'compiler test programs'],
  ['$stdlib_modules', 'stdlib modules'],
  ['$targets', 'tested targets'],
  ['$registry_packages', 'registry packages'],
] as const;
EOF

echo "release facts → $OUT"
