#!/usr/bin/env python3
"""Turn a PSF console font into unikernel/boot/font8x16.c.

The unikernel's framebuffer console needs glyphs, and a UEFI machine
gives it a pixel buffer and nothing else — no VGA text memory, no font
in ROM. So one has to be in the image.

Spleen is used because it is DRAWN at 8x16 rather than scaled to it: a
TTF rasterised this small loses the strokes that tell 'g' from 'q', and
the console it produces is one you squint at when something has gone
wrong on a machine with no other output. It is BSD-2-clause, which is
compatible with this project and requires the notice that
unikernel/boot/font8x16.c carries.

Usage:
    tools/mkfont8x16.py /path/to/spleen-8x16.psfu > unikernel/boot/font8x16.c

The .psfu ships gzipped on Debian and Ubuntu:
    zcat /usr/share/consolefonts/spleen-8x16.psfu.gz > spleen-8x16.psfu
"""

import struct
import sys

PSF1_MAGIC = 0x0436           # two bytes, little-endian
PSF2_MAGIC = 0x864AB572
FIRST, LAST = 32, 126          # printable ASCII; the console maps the rest to '?'


def read_psf(path):
    """Both PSF generations, because which one a distribution ships is
    not something the caller should have to know. PSF1 is 8 pixels wide
    by definition; PSF2 says so in its header and is checked."""
    with open(path, "rb") as fh:
        blob = fh.read()

    if struct.unpack_from("<H", blob, 0)[0] == PSF1_MAGIC:
        mode, charsize = struct.unpack_from("<BB", blob, 2)
        headersize = 4
        width, height = 8, charsize
        length = 512 if mode & 0x01 else 256
    elif struct.unpack_from("<I", blob, 0)[0] == PSF2_MAGIC:
        _, _, headersize, _, length, charsize, height, width = \
            struct.unpack_from("<8I", blob, 0)
    else:
        sys.exit(f"{path}: not a PSF font")

    if (width, height) != (8, 16):
        sys.exit(f"{path}: font is {width}x{height}, this console wants 8x16")
    if charsize != 16:
        sys.exit(f"{path}: {charsize} bytes per glyph, expected 16")
    if length <= LAST:
        sys.exit(f"{path}: only {length} glyphs, need at least {LAST + 1}")

    return [blob[headersize + i * charsize: headersize + (i + 1) * charsize]
            for i in range(length)]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    glyphs = read_psf(sys.argv[1])

    out = sys.stdout.write
    out('''/*
 * NURL unikernel — unikernel/boot/font8x16.c
 *
 * GENERATED by tools/mkfont8x16.py from the Spleen 8x16 console font.
 * Edit the generator, not this file.
 *
 * Spleen is Copyright (c) 2018-2024 Frederic Cambus <fred@statdns.com>
 * and distributed under the BSD 2-Clause License:
 *
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions
 *   are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 *
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 *
 * One byte per pixel row, most significant bit leftmost, sixteen rows
 * per glyph, for the printable ASCII range %d..%d. The console maps
 * everything outside it to '?' rather than indexing past the end.
 */

#include "font8x16.h"

const unsigned char font8x16[FONT8X16_COUNT][16] = {
''' % (FIRST, LAST))

    for code in range(FIRST, LAST + 1):
        rows = glyphs[code]
        label = "space" if code == 32 else repr(chr(code))
        out("    { %s },  /* %3d %s */\n"
            % (", ".join("0x%02X" % b for b in rows), code, label))

    out("};\n")


if __name__ == "__main__":
    main()
