#!/bin/sh
# ============================================================
#  packages/torchpt — test suite
#
#  The oracle is `torch.load` itself: fixtures are generated by
#  tests/make_fixtures.py, which writes both the .pt files and the
#  values torch reads back out of them. torchpt must reproduce every
#  tensor — name, dtype, shape and every element — byte for byte.
#
#  Covered by the fixtures: every storage dtype, pickle protocols 2
#  through 5 (protocol 4+ switches to FRAME / SHORT_BINUNICODE /
#  MEMOIZE / STACK_GLOBAL), nested training-checkpoint dicts, tensors
#  sharing one storage, non-contiguous views (transpose, column slice),
#  zero-element and scalar tensors.
#
#  Plus: malformed inputs must be clean errors, never crashes.
#
#  Needs a python with torch (any CPU build) — set PYTORCH_PY, or the
#  repo's .venv-oracle is used when present. Without one the oracle
#  steps SKIP and only the malformed-input battery runs.
#
#  Run from the package dir:  ./tests/torchpt_test.sh
# ============================================================
set -u
cd "$(dirname "$0")/.."
REPO_ROOT="$(cd ../.. && pwd)"

if [ -n "${NURL:-}" ]; then :;
elif [ -x "$REPO_ROOT/nurl.sh" ]; then NURL="$REPO_ROOT/nurl.sh"; export NURL_STDLIB="${NURL_STDLIB:-$REPO_ROOT}";
else NURL="nurl"; fi

if [ -n "${PYTORCH_PY:-}" ]; then :;
elif [ -x "$REPO_ROOT/.venv-oracle/bin/python" ]; then PYTORCH_PY="$REPO_ROOT/.venv-oracle/bin/python";
else PYTORCH_PY=""; fi

WORK="$(mktemp -d -t torchpt.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
PASS=0; FAIL=0; SKIP=0
ok()   { echo "  PASS $1"; PASS=$((PASS+1)); }
bad()  { echo "  FAIL $1"; FAIL=$((FAIL+1)); }
skip() { echo "  SKIP $1"; SKIP=$((SKIP+1)); }

echo "[1/4] build"
if ! $NURL src/main.nu "$WORK/torchpt" >/dev/null 2>"$WORK/build.err"; then
    echo "  build FAILED"; cat "$WORK/build.err"; exit 1
fi
PT="$WORK/torchpt"

echo "[2/4] fixtures"
if [ -z "$PYTORCH_PY" ] || ! "$PYTORCH_PY" -c "import torch" 2>/dev/null; then
    skip "no python+torch — set PYTORCH_PY to run the oracle comparison"
    HAVE_ORACLE=0
else
    if "$PYTORCH_PY" tests/make_fixtures.py "$WORK/fix" >"$WORK/gen.log" 2>&1; then
        ok "$(cat "$WORK/gen.log")"
        HAVE_ORACLE=1
    else
        bad "fixture generation"; cat "$WORK/gen.log"; HAVE_ORACLE=0
    fi
fi

echo "[3/4] every tensor of every fixture matches torch.load"
if [ "$HAVE_ORACLE" = "1" ]; then
    : > "$WORK/nurl.txt"
    for f in "$WORK"/fix/*.pt; do
        base="$(basename "$f")"
        "$PT" dump "$f" | sed "s|^|$base |" >> "$WORK/nurl.txt" || bad "dump $base"
    done
    # trailing-whitespace-insensitive: a zero-element tensor has no values
    sed -e 's/[[:space:]]*$//' "$WORK/fix/oracle.txt" | sort > "$WORK/a.txt"
    sed -e 's/[[:space:]]*$//' "$WORK/nurl.txt"       | sort > "$WORK/b.txt"
    if cmp -s "$WORK/a.txt" "$WORK/b.txt"; then
        ok "$(wc -l < "$WORK/a.txt" | tr -d ' ') tensors identical to torch"
    else
        bad "tensor values differ from torch"
        diff "$WORK/a.txt" "$WORK/b.txt" | head -20
    fi

    # views must be FLAGGED as views, not silently treated as dense
    if "$PT" tensors "$WORK/fix/views.pt" | grep -q "col_slice.*\[view\]" &&
       "$PT" tensors "$WORK/fix/views.pt" | grep -q "transposed.*\[view\]"; then
        ok "non-contiguous views are reported as views"
    else
        bad "views not flagged"
        "$PT" tensors "$WORK/fix/views.pt"
    fi
else
    skip "oracle comparison"
fi

echo "[4/4] malformed input is an error, not a crash"
mal_check() {  # name, file
    out="$("$PT" info "$2" 2>&1)"; rc=$?
    if [ $rc -ne 0 ] && [ -n "$out" ]; then ok "$1 → $out"
    elif [ $rc -eq 0 ]; then bad "$1 accepted a bad file"
    else bad "$1 died without a message (rc=$rc)"; fi
}

printf 'not a zip at all, nowhere near one' > "$WORK/junk.pt"
mal_check "not a zip" "$WORK/junk.pt"

printf '' > "$WORK/empty.pt"
mal_check "empty file" "$WORK/empty.pt"

if [ "$HAVE_ORACLE" = "1" ]; then
    # a zip that is fine but holds no data.pkl
    "$PYTORCH_PY" - "$WORK" <<'PY'
import sys, zipfile
w = sys.argv[1]
with zipfile.ZipFile(w + "/nopkl.pt", "w") as z:
    z.writestr("archive/version", "3\n")
PY
    mal_check "zip without data.pkl" "$WORK/nopkl.pt"

    # truncate a real checkpoint mid-storage: the central directory goes
    # with it, so this must fail at open rather than read past the end
    head -c 900 "$WORK/fix/nested.pt" > "$WORK/trunc.pt"
    mal_check "truncated checkpoint" "$WORK/trunc.pt"

    # a pickle that is valid pickle but not a checkpoint
    "$PYTORCH_PY" - "$WORK" <<'PY'
import sys, zipfile, pickle
w = sys.argv[1]
with zipfile.ZipFile(w + "/notorch.pt", "w") as z:
    z.writestr("archive/data.pkl", pickle.dumps({"a": [1, 2, 3], "b": "text"}, protocol=2))
    z.writestr("archive/version", "3\n")
PY
    out="$("$PT" info "$WORK/notorch.pt" 2>&1)"
    if echo "$out" | grep -q "tensors: 0"; then ok "tensor-free pickle reads as 0 tensors"
    else bad "tensor-free pickle: $out"; fi
fi

echo
echo "torchpt: $PASS passed, $FAIL failed, $SKIP skipped"
[ "$FAIL" -eq 0 ]
