// pkg_pack_basic.nu — what pkg_pack decides is package SOURCE.
//
// Builds a temp project holding one of everything the packer has to judge,
// packs it, then gunzips + tar_parses the result and checks membership
// (dir_list order isn't deterministic, so this asserts presence/absence,
// not order).
//
// The contract, and why each half of it exists:
//
//   * `deps/` and `nurl.lock` are installed state, never source.
//   * Build output goes by extension (`.ll`, `.o`, `.exe`, …) AND by
//     content: the binary `nurlpkg build` produces on Linux and macOS is
//     named after the package and has NO extension, so an extensionless
//     file whose first bytes are an executable image is build output too.
//     Without that, publishing shipped a 540 KB ELF to every user and the
//     tarball's checksum depended on whether the publisher had built.
//   * A dot-prefixed name is NOT excluded wholesale. That rule dropped
//     `mermaid-server`'s `.templates/` — the themes it loads at startup —
//     producing a package that installed and then refused to run, while
//     `--dry-run` reported every gate passed. Only VCS/editor/toolchain
//     names are excluded by name.
//   * What the package itself calls non-source is honoured: `.gitignore`,
//     read per directory as the walk descends, the way git applies it.
//     That is where `yoloe-demo` keeps the 900 KB test frame its own
//     tooling generates, in `tests/`, not at the root.

$ `stdlib/std/fs.nu`
$ `stdlib/ext/pkg_publish.nu`
$ `stdlib/ext/compress.nu`
$ `stdlib/ext/tar.nu`
$ `stdlib/core/string.nu`
$ `stdlib/core/vec.nu`

@ ignore_io ! v IoErr r → v { ?? r { T _ → {} F _ → {} } }

@ wfile s path s content → v { ( ignore_io ( write_file path content ) ) }

// A file whose first four bytes are the ELF magic — a built binary.
@ welf s path → v {
    : ( Vec u ) b ( vec_new [u] )
    ( vec_push [u] b # u 127 )
    ( vec_push [u] b # u 69 )
    ( vec_push [u] b # u 76 )
    ( vec_push [u] b # u 70 )
    ( vec_push [u] b # u 1 )
    ( ignore_io ( write_file_bytes path b ) )
    ( vec_free [u] b )
}

@ has_entry ( Vec TarEntry ) ents s want → b {
    : i n ( vec_len [TarEntry] ents )
    : ~ i k 0
    ~ < k n {
        ?? ( vec_get [TarEntry] ents k ) {
            T e → { ? != 0 ( nurl_str_eq ( string_data . e path ) want ) { ^ T } {} }
            F _ → {}
        }
        = k + k 1
    }
    ^ F
}

@ pb s label b v → v {
    ( nurl_print label )
    ( nurl_print `=` )
    ? v { ( nurl_println `T` ) } { ( nurl_println `F` ) }
}

@ main → i {
    : s root `/tmp/nurl_pack_test`
    ( ignore_io ( dir_remove_all root ) )
    ( ignore_io ( dir_create_all `/tmp/nurl_pack_test/src` ) )
    ( ignore_io ( dir_create_all `/tmp/nurl_pack_test/deps/foo` ) )
    ( ignore_io ( dir_create_all `/tmp/nurl_pack_test/.templates` ) )
    ( ignore_io ( dir_create_all `/tmp/nurl_pack_test/.git` ) )
    ( ignore_io ( dir_create_all `/tmp/nurl_pack_test/tests` ) )

    ( wfile `/tmp/nurl_pack_test/nurl.toml` `[package]
name = "demo"
version = "0.1.0"
` )
    ( wfile `/tmp/nurl_pack_test/src/lib.nu` `@ answer -> i { ^ 42 }
` )
    ( wfile `/tmp/nurl_pack_test/deps/foo/junk.nu` `installed dep
` )
    ( wfile `/tmp/nurl_pack_test/nurl.lock` `installed state
` )
    // Data the package ships, under a dot-prefixed directory.
    ( wfile `/tmp/nurl_pack_test/.templates/default.toml` `name = "default"
` )
    // Version control, and the package's own ignore list.
    ( wfile `/tmp/nurl_pack_test/.git/config` `[core]
` )
    ( wfile `/tmp/nurl_pack_test/.gitignore` `# built locally
/demo
*.ll
` )
    ( wfile `/tmp/nurl_pack_test/tests/.gitignore` `generated.rgb
` )
    ( wfile `/tmp/nurl_pack_test/tests/smoke.nu` `@ t -> i { ^ 0 }
` )
    ( wfile `/tmp/nurl_pack_test/tests/generated.rgb` `generated by the suite
` )
    // Build output: by extension, and by content with no extension.
    ( wfile `/tmp/nurl_pack_test/demo.ll` `; ModuleID = 'demo'
` )
    ( welf `/tmp/nurl_pack_test/demo` )

    : !( Vec u ) PackErr pr ( pkg_pack root )
    ?? pr {
        F e → ( nurl_print ( pack_err_name e ) )
        T gz → {
            ( nurl_print `gz_nonempty=` ) ? > ( vec_len [u] gz ) 0 { ( nurl_print `T\n` ) } { ( nurl_print `F\n` ) }
            : !( Vec u ) CompressErr ur ( gzip_decompress gz )
            ?? ur {
                F e → ( nurl_print ( compress_err_name e ) )
                T raw → {
                    : !( Vec TarEntry ) TarErr tp ( tar_parse raw )
                    ?? tp {
                        F e → ( nurl_print ( tar_err_name e ) )
                        T ents → {
                            ( nurl_print `count=` ) ( nurl_println_int ( vec_len [TarEntry] ents ) )
                            // Source, all of it packed.
                            ( pb `has_nurl.toml` ( has_entry ents `nurl.toml` ) )
                            ( pb `has_src/lib.nu` ( has_entry ents `src/lib.nu` ) )
                            ( pb `has_tests/smoke.nu` ( has_entry ents `tests/smoke.nu` ) )
                            ( pb `has_dot_dir_data` ( has_entry ents `.templates/default.toml` ) )
                            // Installed state.
                            ( pb `excl_deps` ( has_entry ents `deps/foo/junk.nu` ) )
                            ( pb `excl_lock` ( has_entry ents `nurl.lock` ) )
                            // Version control.
                            ( pb `excl_git_dir` ( has_entry ents `.git/config` ) )
                            ( pb `excl_gitignore` ( has_entry ents `.gitignore` ) )
                            // Build output, both ways of spotting it.
                            ( pb `excl_ll` ( has_entry ents `demo.ll` ) )
                            ( pb `excl_bare_binary` ( has_entry ents `demo` ) )
                            // What the package's own ignore list claims.
                            ( pb `excl_gitignored_nested` ( has_entry ents `tests/generated.rgb` ) )
                            ( tar_entries_free ents )
                        }
                    }
                    ( vec_free [u] raw )
                }
            }
            ( vec_free [u] gz )
        }
    }
    ( ignore_io ( dir_remove_all root ) )
    ( nurl_println `done` )
    ^ 0
}
